# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('serial', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='numéro de série')),
                ('purchase_reference', models.CharField(blank=True, max_length=40, verbose_name="facture d'achat")),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="date d'achat")),
                ('sale_reference', models.CharField(blank=True, max_length=40, verbose_name='facture de vente')),
                ('delivery_reference', models.CharField(blank=True, max_length=40, verbose_name='bon de livraison')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='date de vente')),
                ('warranty_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='fin de garantie')),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('sold', 'Vendu'), ('returned', 'Retourné'), ('scrapped', 'Réformé')], db_index=True, default='in_stock', max_length=10, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='partners.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'numéro de série',
                'verbose_name_plural': 'numéros de série',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='désignation')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('is_default', models.BooleanField(default=False, verbose_name='dépôt par défaut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'dépôt',
                'verbose_name_plural': 'dépôts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjust', 'Ajustement'), ('return_in', 'Retour client'), ('return_out', 'Retour fournisseur')], max_length=12, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='coût unitaire')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='document')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observation')),
                ('moved_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ('-moved_at',),
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantité')),
                ('location', models.CharField(blank=True, max_length=60, verbose_name='emplacement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
