# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('category', models.CharField(choices=[('supplier', 'Fournisseurs'), ('customer', 'Clients'), ('stock', 'Stock'), ('warranty', 'Garanties'), ('contract', 'Contrats'), ('tender', 'Marchés')], db_index=True, max_length=12, verbose_name='catégorie')),
                ('code', models.CharField(choices=[('order_late', 'Commande en retard'), ('supplier_invoice_due', 'Facture fournisseur échue'), ('customer_invoice_overdue', 'Facture client impayée'), ('quote_no_answer', 'Devis sans réponse'), ('receivable_high', 'Créance importante'), ('stock_low', 'Stock faible'), ('stock_out', 'Rupture de stock'), ('warranty_expiring', "Garantie proche de l'expiration")], db_index=True, max_length=30, verbose_name='type')),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], db_index=True, default='medium', max_length=10, verbose_name='urgence')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('message_ar', models.TextField(blank=True, verbose_name='الرسالة')),
                ('entity_type', models.CharField(blank=True, max_length=40, verbose_name='entité')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='identifiant')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='lien')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='lue')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='traitée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'alerte',
                'verbose_name_plural': 'alertes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['code', 'entity_id'], name='alerts_aler_code_a2671a_idx')],
            },
        ),
    ]
