# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('validate', 'Validation'), ('cancel', 'Annulation'), ('read', 'Consultation'), ('login', 'Connexion')], db_index=True, max_length=10, verbose_name='opération')),
                ('model_name', models.CharField(db_index=True, max_length=60, verbose_name='objet')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='identifiant')),
                ('object_label', models.CharField(blank=True, max_length=200, verbose_name='libellé')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='modifications')),
                ('path', models.CharField(blank=True, max_length=250, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=8, verbose_name='méthode')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=200, verbose_name='appareil')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée de journal',
                'verbose_name_plural': "journal d'activité",
                'ordering': ('-created_at',),
            },
        ),
    ]
