# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validé'), ('partial', 'Partiel'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('refused', 'Refusé')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='partners.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'avoir',
                'verbose_name_plural': 'avoirs',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance')),
                ('payment_term', models.CharField(choices=[('cash', 'Comptant'), ('15', '15 jours'), ('30', '30 jours'), ('45', '45 jours'), ('60', '60 jours'), ('90', '90 jours')], default='30', max_length=10, verbose_name='conditions de paiement')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant payé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='timbre fiscal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.delivery')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'facture client',
                'verbose_name_plural': 'factures clients',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.customerinvoice'),
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.customerinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance')),
                ('payment_term', models.CharField(choices=[('cash', 'Comptant'), ('15', '15 jours'), ('30', '30 jours'), ('45', '45 jours'), ('60', '60 jours'), ('90', '90 jours')], default='30', max_length=10, verbose_name='conditions de paiement')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant payé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('supplier_reference', models.CharField(blank=True, max_length=40, verbose_name='référence fournisseur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.purchaseorder')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.goodsreceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'facture fournisseur',
                'verbose_name_plural': 'factures fournisseurs',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('direction', models.CharField(choices=[('in', 'Encaissement client'), ('out', 'Décaissement fournisseur')], db_index=True, max_length=3, verbose_name='sens')),
                ('paid_on', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('card', 'Carte'), ('bill', 'Traite'), ('other', 'Autre')], default='transfer', max_length=10, verbose_name='mode de paiement')),
                ('bank', models.CharField(blank=True, max_length=120, verbose_name='banque')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='référence')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.customer')),
                ('customer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.customerinvoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.supplierinvoice')),
            ],
            options={
                'verbose_name': 'règlement',
                'verbose_name_plural': 'règlements',
                'ordering': ('-paid_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.supplierinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
