# Generated by Django 5.1.5 on 2026-08-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='réglé'),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de règlement'),
        ),
    ]
