# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='marque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'marque',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='désignation')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='التسمية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='code')),
                ('designation', models.CharField(db_index=True, max_length=200, verbose_name='désignation')),
                ('designation_ar', models.CharField(blank=True, max_length=200, verbose_name='التسمية')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modèle')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='référence')),
                ('unit', models.CharField(choices=[('piece', 'Unité'), ('box', 'Boîte'), ('pack', 'Paquet'), ('kg', 'Kilogramme'), ('m', 'Mètre'), ('l', 'Litre'), ('service', 'Prestation')], default='piece', max_length=10, verbose_name='unité')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="prix d'achat")),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix de vente')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='seuil minimum')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='seuil maximum')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='garantie (mois)')),
                ('has_serial', models.BooleanField(default=False, verbose_name='suivi par numéro de série')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('designation',),
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('supplier_reference', models.CharField(blank=True, max_length=120, verbose_name='référence fournisseur')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="prix d'achat")),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='délai (jours)')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='garantie (mois)')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='dernier achat')),
                ('purchased_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantité achetée')),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix moyen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='partners.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'produit fournisseur',
                'verbose_name_plural': 'produits fournisseurs',
                'ordering': ('price',),
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
