// Données officielles du Code Géographique National 2021 (wilayas + communes).
// Généré automatiquement — ne pas éditer à la main, régénérer depuis la source si besoin.

export const WILAYAS = [
  { code: "01", fr: "Adrar", ar: "أدرار" },
  { code: "02", fr: "Chlef", ar: "الشلف" },
  { code: "03", fr: "Laghouat", ar: "األغواط" },
  { code: "04", fr: "Oum El Bouaghi", ar: "أم البواقي" },
  { code: "05", fr: "Batna", ar: "باتنة" },
  { code: "06", fr: "Bejaia", ar: "بجاية" },
  { code: "07", fr: "Biskra", ar: "بسكرة" },
  { code: "08", fr: "Bechar", ar: "بشار" },
  { code: "09", fr: "Blida", ar: "بليدة" },
  { code: "10", fr: "Bouira", ar: "بويرة" },
  { code: "11", fr: "Tamenghasset", ar: "تمنراست" },
  { code: "12", fr: "Tebessa", ar: "تبسة" },
  { code: "13", fr: "Tlemcen", ar: "تلمسان" },
  { code: "14", fr: "Tiaret", ar: "تيارت" },
  { code: "15", fr: "Tizi Ouzou", ar: "تيزي وزو" },
  { code: "16", fr: "Alger", ar: "الجزائر" },
  { code: "17", fr: "Djelfa", ar: "جلفة" },
  { code: "18", fr: "Jijel", ar: "جيجل" },
  { code: "19", fr: "Setif", ar: "سطيف" },
  { code: "20", fr: "Saida", ar: "سعيدة" },
  { code: "21", fr: "Skikda", ar: "سكيكدة" },
  { code: "22", fr: "Sidi Bel Abbes", ar: "سيدي بلعباس" },
  { code: "23", fr: "Annaba", ar: "عنابة" },
  { code: "24", fr: "Guelma", ar: "قالمة" },
  { code: "25", fr: "Constantine", ar: "قسنطينة" },
  { code: "26", fr: "Medea", ar: "المدية" },
  { code: "27", fr: "Mostaganem", ar: "مستغانم" },
  { code: "28", fr: "M'Sila", ar: "المسيلة" },
  { code: "29", fr: "Mascara", ar: "معسكر" },
  { code: "30", fr: "Ouargla", ar: "ورقلة" },
  { code: "31", fr: "Oran", ar: "وهران" },
  { code: "32", fr: "El Bayadh", ar: "البيض" },
  { code: "33", fr: "Illizi", ar: "إليزي" },
  { code: "34", fr: "Bordj Bou Arreridj", ar: "برج بوعريريج" },
  { code: "35", fr: "Boumerdes", ar: "بومرداس" },
  { code: "36", fr: "El Tarf", ar: "الطارف" },
  { code: "37", fr: "Tindouf", ar: "تندوف" },
  { code: "38", fr: "Tissemsilt", ar: "تيسمسيلت" },
  { code: "39", fr: "El Oued", ar: "الوادي" },
  { code: "40", fr: "Khenchela", ar: "خنشلة" },
  { code: "41", fr: "Souk Ahras", ar: "سوق أهراس" },
  { code: "42", fr: "Tipaza", ar: "تيبازة" },
  { code: "43", fr: "Mila", ar: "ميلة" },
  { code: "44", fr: "Ain Defla", ar: "عين الدفلى" },
  { code: "45", fr: "Naama", ar: "النعامة" },
  { code: "46", fr: "Ain Temouchent", ar: "عين تموشنت" },
  { code: "47", fr: "Ghardaia", ar: "غرداية" },
  { code: "48", fr: "Relizane", ar: "غليزان" },
  { code: "49", fr: "Timimoun", ar: "تيميمون" },
  { code: "50", fr: "Bordj Badji Mokhtar", ar: "برج باج مختار" },
  { code: "51", fr: "Ouled Djellal", ar: "أولاد جلال" },
  { code: "52", fr: "Beni Abbes", ar: "بني عباس" },
  { code: "53", fr: "In Salah", ar: "إن صالح" },
  { code: "54", fr: "In Guezzam", ar: "إن قزام" },
  { code: "55", fr: "Touggourt", ar: "توقرت" },
  { code: "56", fr: "Djanet", ar: "جانت" },
  { code: "57", fr: "El Megaier", ar: "المغير" },
  { code: "58", fr: "El Meniaa", ar: "المنيعة" },
  { code: "59", fr: "Aflou", ar: "آفلو" },
  { code: "60", fr: "Barika", ar: "بريكة" },
  { code: "61", fr: "El Kantara", ar: "القنطرة" },
  { code: "62", fr: "Bir El Ater", ar: "بئر العاتر" },
  { code: "63", fr: "El Aricha", ar: "العريشة" },
  { code: "64", fr: "Ksar Chellala", ar: "قصر الشاللة" },
  { code: "65", fr: "Ain Oussera", ar: "عين وسارة" },
  { code: "66", fr: "Messaad", ar: "مسعد" },
  { code: "67", fr: "Ksar El Boukhari", ar: "قصر البخاري" },
  { code: "68", fr: "Bousaada", ar: "بوسعادة" },
  { code: "69", fr: "El Abiodh Sidi Cheikh", ar: "الأبيض سيدي الشيخ" },
]

export const COMMUNES_BY_WILAYA = {
  "01": [
    { fr: "Adrar", ar: "أدرار" },
    { fr: "Tamest", ar: "تاماست" },
    { fr: "Reggane", ar: "رقان" },
    { fr: "In Zeghmir", ar: "ان زغمير" },
    { fr: "Tit", ar: "تيت" },
    { fr: "Tsabit", ar: "تسابيت" },
    { fr: "Zaouiet Kounta", ar: "زاوية كنته" },
    { fr: "Aoulef", ar: "أولف" },
    { fr: "Timokten", ar: "تيمقتن" },
    { fr: "Tamantit", ar: "تامنطيت" },
    { fr: "Fenoughil", ar: "فنوغيل" },
    { fr: "Sali", ar: "سالى" },
    { fr: "Akabli", ar: "أقبلى" },
    { fr: "Ouled Ahmed Timmi", ar: "أوالد أحمد تيمى" },
    { fr: "Bouda", ar: "بودة" },
    { fr: "Sebaa", ar: "السبع" },
  ],
  "02": [
    { fr: "Chlef", ar: "الشلف" },
    { fr: "Tenes", ar: "تنس" },
    { fr: "Benairia", ar: "بنايرية" },
    { fr: "El Karimia", ar: "الكريمية" },
    { fr: "Tadjena", ar: "تاجنة" },
    { fr: "Taougrite", ar: "تاوقريت" },
    { fr: "Beni Haoua", ar: "بنى حواء" },
    { fr: "Sobha", ar: "صبحة" },
    { fr: "Harchoun", ar: "حرشون" },
    { fr: "Ouled Fares", ar: "أوالد فارس" },
    { fr: "Sidi Akkacha", ar: "سيدى عكاشة" },
    { fr: "Boukadir", ar: "بوقادير" },
    { fr: "Beni Rached", ar: "بنى راشد" },
    { fr: "Talassa", ar: "تلعصة" },
    { fr: "El Harenfa", ar: "الهرانفة" },
    { fr: "Oued Goussine", ar: "وادى قوسين" },
    { fr: "Dahra", ar: "الظهرة" },
    { fr: "Ouled Abbes", ar: "أوالد عباس" },
    { fr: "Sendjas", ar: "سنجاس" },
    { fr: "Zeboudja", ar: "الزبوجة" },
    { fr: "Oued Sly", ar: "وادى سلى" },
    { fr: "Abou El Hassen", ar: "الحسن أبو" },
    { fr: "El Marsa", ar: "المرسى" },
    { fr: "Chettia", ar: "الشطية" },
    { fr: "Sidi Abderrahmane", ar: "سيدي عبد الرحمان" },
    { fr: "Moussadek", ar: "مصدق" },
    { fr: "El Hadjadj", ar: "الحجاج" },
    { fr: "Medjadja Labiod", ar: "االبيض مجاجة" },
    { fr: "Oued Fodda", ar: "وادى الفضة" },
    { fr: "Ouled Ben Aek", ar: "أوالد بن عبد القادر" },
    { fr: "Bouzghaia", ar: "بوزغاية" },
    { fr: "Ain Merane", ar: "عين مران" },
    { fr: "Oum El Drou", ar: "الذروع أم" },
    { fr: "Breira", ar: "بريرة" },
    { fr: "Beni Bouattab", ar: "بنى بوعتاب" },
  ],
  "03": [
    { fr: "Laghouat", ar: "األغواط" },
    { fr: "Ksar El Hirane", ar: "الحيران قصر" },
    { fr: "Benacer Ben Chohra", ar: "بن ناصر بن شهرة" },
    { fr: "Sidi Makhlouf", ar: "سيدي مخلوف" },
    { fr: "Hassi Dalaa", ar: "حاسى الدالعة" },
    { fr: "Hassi R'Mel", ar: "الرمل حاسى" },
    { fr: "Ain Mahdi", ar: "عين ماضي" },
    { fr: "Tadjemout", ar: "تاجموت" },
    { fr: "El Kheneg", ar: "الخنق" },
    { fr: "Sebgag", ar: "سبقاق" },
    { fr: "El Assafia", ar: "العسافية" },
    { fr: "El Houita", ar: "الحويطة" },
  ],
  "04": [
    { fr: "Oum El Bouaghi", ar: "أم البواقي" },
    { fr: "Ain Beida", ar: "عين البيضاء" },
    { fr: "Ain M'Lila", ar: "مليلة عين" },
    { fr: "Behir Chergui", ar: "بحير الشرقي" },
    { fr: "El Amiria", ar: "العامرية" },
    { fr: "Sigus", ar: "سيقوس" },
    { fr: "El Belala", ar: "الباللة" },
    { fr: "Ain Babouche", ar: "عين ببوش" },
    { fr: "Berriche", ar: "بريش" },
    { fr: "Ouled Hamla", ar: "أوالد حملة" },
    { fr: "El Dhalaa", ar: "الضلعة" },
    { fr: "Ain Kercha", ar: "عين كرشة" },
    { fr: "Henchir Toumghani", ar: "هنشير تومغانى" },
    { fr: "El Djazia", ar: "الجازية" },
    { fr: "Ain Diss", ar: "عين الديس" },
    { fr: "F'Kirina", ar: "فكيرينة" },
    { fr: "Souk Naamane", ar: "سوق نعمان" },
    { fr: "El Zorg", ar: "الزرق" },
    { fr: "El Fedjoudj Boughara Saoudi", ar: "سعودى بوغرارة الفجوج" },
    { fr: "Ouled Zouai", ar: "أوالد زواى" },
    { fr: "Bir Chouhada", ar: "بئر الشهداء" },
    { fr: "Ksar Sbahi", ar: "قصر الصباحى" },
    { fr: "Oued Nini", ar: "وادى نينى" },
    { fr: "Meskiana", ar: "مسكيانة" },
    { fr: "Ain Fakroun", ar: "عين فكرون" },
    { fr: "El Rahia", ar: "الرحية" },
    { fr: "Ain Zitoun", ar: "عين الزيتون" },
    { fr: "Ouled Gacem", ar: "أوالد قاسم" },
    { fr: "El Harmilia", ar: "الحرملية" },
  ],
  "05": [
    { fr: "Batna", ar: "باتنة" },
    { fr: "Ghassira", ar: "غسيرة" },
    { fr: "Maafa", ar: "معافة" },
    { fr: "Merouana", ar: "مروانة" },
    { fr: "Seriana", ar: "سريانة" },
    { fr: "Menaa", ar: "منعة" },
    { fr: "El Madher", ar: "المعذر" },
    { fr: "Tazoult", ar: "تازولت" },
    { fr: "N'Gaous", ar: "نقاوس" },
    { fr: "El Guigba", ar: "القيقبة" },
    { fr: "Inoughissene", ar: "اينوغيسن" },
    { fr: "El Ouyoun Assafir", ar: "عيون العصا فير" },
    { fr: "Djerma", ar: "جرمة" },
    { fr: "Arris", ar: "أريس" },
    { fr: "Kimmel", ar: "كيمل" },
    { fr: "Ain Djasser", ar: "عين جاسر" },
    { fr: "Ouled Sellam", ar: "أوالد سالم" },
    { fr: "Tigherghar", ar: "تغرغار" },
    { fr: "Ain Yagout", ar: "عين ياقوت" },
    { fr: "Fesdis", ar: "فسديس" },
    { fr: "Sefiane", ar: "سفيان" },
    { fr: "El Rahbat", ar: "الرحبات" },
    { fr: "Tighanimine", ar: "تغانمين" },
    { fr: "Lemsane", ar: "لمسان" },
    { fr: "Ksar Belezma", ar: "قصر بالزمة" },
    { fr: "Foum El Toub", ar: "فم الطوب" },
    { fr: "Beni Foudhala El Hakania", ar: "الحقانية فضالة بنى" },
    { fr: "Oued El Ma", ar: "الماء وادى" },
    { fr: "Talkhamt", ar: "تالخمت" },
    { fr: "Bouzina", ar: "بوزينة" },
    { fr: "Chemora", ar: "شمرة" },
    { fr: "Oued Chaaba", ar: "وادى الشعبة" },
    { fr: "Taxlent", ar: "تاكسالنت" },
    { fr: "Gosbat", ar: "القصبات" },
    { fr: "Ouled Aouf", ar: "أوالد عوف" },
    { fr: "Boumagueur", ar: "بومقر" },
    { fr: "T'Kout", ar: "تكوت" },
    { fr: "Ain Touta", ar: "عين التوتة" },
    { fr: "Hidoussa", ar: "حيدوسة" },
    { fr: "Teniet El Abed", ar: "العابد ثنية" },
    { fr: "Oued Taga", ar: "وادى الطا قة" },
    { fr: "Ouled Fadhel", ar: "أوالد فاضل" },
    { fr: "Timgad", ar: "تيمقاد" },
    { fr: "Ras El Aioun", ar: "العيون رأس" },
    { fr: "Chir", ar: "شير" },
    { fr: "Ouled Si Slimane", ar: "أوالد سى سليمان" },
    { fr: "Zanat El Beida", ar: "البيضاء زانة" },
    { fr: "El Hassi", ar: "الحاسى" },
    { fr: "Lazrou", ar: "الزرو" },
    { fr: "Boumia", ar: "بومية" },
    { fr: "Boulhilet", ar: "بولهيالت" },
    { fr: "Larbaa", ar: "الرباع" },
  ],
  "06": [
    { fr: "Bejaia", ar: "بجاية" },
    { fr: "Amizour", ar: "أميزور" },
    { fr: "Feraoun", ar: "فرعون" },
    { fr: "Taourirt Ighil", ar: "تاوريرت إغيل" },
    { fr: "Chellata", ar: "شالطة" },
    { fr: "Tamokra", ar: "تامقرة" },
    { fr: "Timezrit", ar: "تيمزريت" },
    { fr: "Souk El Tenine", ar: "سوق االثنين" },
    { fr: "M'Cisna", ar: "مسيسنة" },
    { fr: "Tinebdar", ar: "تينبدار" },
    { fr: "Tichy", ar: "تيشي" },
    { fr: "Semaoun", ar: "سمعون" },
    { fr: "Kendira", ar: "كنديرة" },
    { fr: "Tifra", ar: "تيفرة" },
    { fr: "Ighram", ar: "إغرم" },
    { fr: "Amalou", ar: "أمالو" },
    { fr: "Ighil Ali", ar: "إغيل علي" },
    { fr: "Ifelain Ilmathen", ar: "إفالين إلماثن" },
    { fr: "Toudja", ar: "توجة" },
    { fr: "Darguina", ar: "درقينة" },
    { fr: "Sidi Ayad", ar: "سيدي عياد" },
    { fr: "Aokas", ar: "أوقاس" },
    { fr: "Beni Djellil", ar: "بني جليل" },
    { fr: "Adekar", ar: "أدكار" },
    { fr: "Akbou", ar: "أقبو" },
    { fr: "Seddouk", ar: "صدوق" },
    { fr: "Tazmalt", ar: "تازمالت" },
    { fr: "Ait R'Zine", ar: "رزين آيت" },
    { fr: "Chemini", ar: "شميني" },
    { fr: "Souk Oufella", ar: "السوق أوفال" },
    { fr: "Taskriout", ar: "تاسكريوت" },
    { fr: "Tibane", ar: "طيبان" },
    { fr: "Tala Hamza", ar: "ثالة حمزة" },
    { fr: "Barbacha", ar: "برباشة" },
    { fr: "Beni Ksila", ar: "بنى كسيلة" },
    { fr: "Ouzellaguen", ar: "أوزالقن" },
    { fr: "Bouhamza", ar: "بوحمزة" },
    { fr: "Beni Melikeche", ar: "بنى مليكش" },
    { fr: "Sidi Aich", ar: "سيدي عيش" },
    { fr: "El Kseur", ar: "القصر" },
    { fr: "Melbou", ar: "مالبو" },
    { fr: "Akfadou", ar: "أكفادو" },
    { fr: "Leflay", ar: "لفالى" },
    { fr: "Kherrata", ar: "خراطة" },
    { fr: "Draa El Kaid", ar: "القايد ذراع" },
    { fr: "Tamridjet", ar: "تامريجت" },
    { fr: "Ait Smail", ar: "آيت اسماعيل" },
    { fr: "Boukhlifa", ar: "بوخليفة" },
    { fr: "Tizi N'Berber", ar: "نبربر تيزى" },
    { fr: "Beni Maouche", ar: "بنى معوش" },
    { fr: "Oued Ghir", ar: "وادى غير" },
    { fr: "Boudjellil", ar: "بوجليل" },
  ],
  "07": [
    { fr: "Biskra", ar: "بسكرة" },
    { fr: "Oumach", ar: "أوماش" },
    { fr: "Chetma", ar: "شتمة" },
    { fr: "Sidi Okba", ar: "سيدي عقبة" },
    { fr: "M'Chouneche", ar: "مشونش" },
    { fr: "El Haouch", ar: "الحوش" },
    { fr: "Ain Naga", ar: "عين الناقة" },
    { fr: "Zeribet El Oued", ar: "الوادى زريبة" },
    { fr: "El Feidh", ar: "الفيض" },
    { fr: "Tolga", ar: "طولقة" },
    { fr: "Lioua", ar: "لواء" },
    { fr: "Lichana", ar: "ليشانة" },
    { fr: "Ourlal", ar: "أورالل" },
    { fr: "M'Lili", ar: "مليلى" },
    { fr: "Foughala", ar: "فوغالة" },
    { fr: "Bordj Ben Azzouz", ar: "برج بن عزوز" },
    { fr: "M'Ziraa", ar: "المزيرعة" },
    { fr: "Bouchagroun", ar: "بوشقرون" },
    { fr: "Mekhadma", ar: "مخادمة" },
    { fr: "El Ghrous", ar: "الغروس" },
    { fr: "El Hadjeb", ar: "الحاجب" },
    { fr: "Khenghet Sidi Nadji", ar: "خنقة سيدي ناجى" },
  ],
  "08": [
    { fr: "Bechar", ar: "بشار" },
    { fr: "Erg Ferradj", ar: "عرق فراج" },
    { fr: "Meridja", ar: "مريجة" },
    { fr: "Lahmar", ar: "األحمر" },
    { fr: "Mechraa Boumediene", ar: "مشرع هوارى بومدين" },
    { fr: "Kenadsa", ar: "قنادسة" },
    { fr: "Taghit", ar: "تاغيت" },
    { fr: "Boukais", ar: "بوقا يس" },
    { fr: "Mogheul", ar: "موغل" },
    { fr: "Abadla", ar: "العبادلة" },
    { fr: "Beni Ounif", ar: "بنى و نيف" },
  ],
  "09": [
    { fr: "Blida", ar: "البليدة" },
    { fr: "Chebli", ar: "الشبلي" },
    { fr: "Bouinan", ar: "بوعينان" },
    { fr: "Oued El Alleug", ar: "العاليق وادى" },
    { fr: "Ouled Yaich", ar: "اوالد يعيش" },
    { fr: "Chrea", ar: "الشريعة" },
    { fr: "El Affroun", ar: "العفرون" },
    { fr: "Chiffa", ar: "الشفة" },
    { fr: "Hammam Melouane", ar: "حمام ملوان" },
    { fr: "Ben Khelil", ar: "بن خليل" },
    { fr: "Soumaa", ar: "الصومعة" },
    { fr: "Mouzaia", ar: "موزاية" },
    { fr: "Souhane", ar: "صوحان" },
    { fr: "Meftah", ar: "مفتاح" },
    { fr: "Ouled Slama", ar: "أوالد سالمة" },
    { fr: "Boufarik", ar: "بوفاريك" },
    { fr: "Larbaa", ar: "االربعاء" },
    { fr: "Oued Djer", ar: "وادى جر" },
    { fr: "Beni Tamou", ar: "بني تامو" },
    { fr: "Bouarfa", ar: "بوعرفة" },
    { fr: "Beni Merad", ar: "بني مراد" },
    { fr: "Bougara", ar: "بوقرة" },
    { fr: "Guerouaou", ar: "قرواو" },
    { fr: "Ain Romana", ar: "عين الرمانة" },
    { fr: "Djebabra", ar: "جبابرة" },
  ],
  "10": [
    { fr: "Bouira", ar: "البويرة" },
    { fr: "El Asnam", ar: "األصنام" },
    { fr: "Guerrouma", ar: "قرومة" },
    { fr: "Souk El Khemis", ar: "الخميس سوق" },
    { fr: "Kadiria", ar: "القادرية" },
    { fr: "Ahnif", ar: "أحنيف" },
    { fr: "Dirah", ar: "ديرة" },
    { fr: "Ait Laaziz", ar: "آيت لعزيز" },
    { fr: "Taghzout", ar: "تاغزوت" },
    { fr: "Raouraoua", ar: "روراوة" },
    { fr: "Mezdour", ar: "مزدور" },
    { fr: "Haizer", ar: "الحيزر" },
    { fr: "Lakhdaria", ar: "األخضرية" },
    { fr: "El Maala", ar: "المعلة" },
    { fr: "El Hachimia", ar: "الهاشمية" },
    { fr: "Aomar", ar: "عومار" },
    { fr: "Chorfa", ar: "الشرفاء" },
    { fr: "Bordj Okhriss", ar: "برج أوخريص" },
    { fr: "El Adjiba", ar: "العجيبة" },
    { fr: "El Hakimia", ar: "الحاكمية" },
    { fr: "El Khabouzia", ar: "الخبوزية" },
    { fr: "Ahl El Ksar", ar: "القصر أهل" },
    { fr: "Bouderbala", ar: "بودربالة" },
    { fr: "Zbarbar", ar: "زبربر" },
    { fr: "Ain El Hadjar", ar: "الحجر عين" },
    { fr: "Djebahia", ar: "جباحية" },
    { fr: "Aghbalou", ar: "أغبالو" },
    { fr: "Taguedite", ar: "تاقديت" },
    { fr: "Ain Turk", ar: "عين الترك" },
    { fr: "Saharidj", ar: "الصهاريج" },
    { fr: "Dechmia", ar: "الدشمية" },
    { fr: "Ridane", ar: "ريدان" },
    { fr: "Bechloul", ar: "بشلول" },
    { fr: "Boukram", ar: "بوكرام" },
    { fr: "Ain Bessam", ar: "عين بسام" },
    { fr: "Bir Ghbalou", ar: "بئر غبالو" },
    { fr: "M'Chedallah", ar: "مشدالة" },
    { fr: "Sour El Ghozlane", ar: "الغزالن سور" },
    { fr: "El Maamora", ar: "المعمورة" },
    { fr: "Ouled Rached", ar: "أوالد راشد" },
    { fr: "Ain Laloui", ar: "عين العلوي" },
    { fr: "Hadjera Zerga", ar: "الحجرة الزرقاء" },
    { fr: "Ath Mansour", ar: "آث منصور" },
    { fr: "El Mokrani", ar: "المقراني" },
    { fr: "Oued El Berdi", ar: "البردي وادى" },
  ],
  "11": [
    { fr: "Tamenghasset", ar: "تامنغست" },
    { fr: "Abalessa", ar: "أباليسا" },
    { fr: "Ideles", ar: "إدلس" },
    { fr: "Tazrouk", ar: "تاظروك" },
    { fr: "In Amguel", ar: "إن أمقل" },
  ],
  "12": [
    { fr: "Tebessa", ar: "تبسة" },
    { fr: "Cheria", ar: "الشريعة" },
    { fr: "Stah Guentis", ar: "سطح قنطيس" },
    { fr: "El Aouinet", ar: "العوينات" },
    { fr: "El Houidjbet", ar: "الحويجبات" },
    { fr: "Safsaf El Ouesra", ar: "الوسرى صفصاف" },
    { fr: "El Hammamet", ar: "الحمامات" },
    { fr: "Bir Mokadem", ar: "بئر مقدم" },
    { fr: "El Kouif", ar: "الكويف" },
    { fr: "Morsott", ar: "مرسط" },
    { fr: "El Ogla", ar: "العقلة" },
    { fr: "Bir Dheheb", ar: "بئر الذهب" },
    { fr: "Gorriguer", ar: "قريقر" },
    { fr: "Bekkaria", ar: "بكارية" },
    { fr: "Boukhadra", ar: "بوخضرة" },
    { fr: "Ouenza", ar: "الونزة" },
    { fr: "El Ma El Biodh", ar: "االبيض الماء" },
    { fr: "Oum Ali", ar: "أم على" },
    { fr: "Thlidjen", ar: "ثليجان" },
    { fr: "Ain Zerga", ar: "عين الزرقاء" },
    { fr: "El Meridj", ar: "المريج" },
    { fr: "Boulhef Dyr", ar: "بولحاف الدير" },
    { fr: "Bedjen", ar: "بجن" },
    { fr: "El Mezeraa", ar: "المزرعة" },
  ],
  "13": [
    { fr: "Tlemcen", ar: "تلمسان" },
    { fr: "Beni Mester", ar: "بنى مستر" },
    { fr: "Ain Tellout", ar: "عين تالوت" },
    { fr: "Remchi", ar: "الرمشى" },
    { fr: "El Fehoul", ar: "الفحول" },
    { fr: "Sabra", ar: "صبرة" },
    { fr: "Ghazaouet", ar: "الغزوات" },
    { fr: "Souani", ar: "السوانى" },
    { fr: "Djebala", ar: "جبالة" },
    { fr: "Oued Lakhdar", ar: "واد لخضر" },
    { fr: "Ain Fezza", ar: "عين فزة" },
    { fr: "Ouled Mimoun", ar: "أوالد ميمون" },
    { fr: "Amieur", ar: "عمير" },
    { fr: "Ain Youcef", ar: "عين يوسف" },
    { fr: "Zenata", ar: "زناتة" },
    { fr: "Beni Snous", ar: "بنى سنوس" },
    { fr: "Bab El Assa", ar: "العسة باب" },
    { fr: "Dar Yaghmouracene", ar: "دار يغمراسن" },
    { fr: "Filaoucene", ar: "فالوسن" },
    { fr: "Azailes", ar: "العزايل" },
    { fr: "Sebaa Chioukh", ar: "السبعة شيوخ" },
    { fr: "Terni Beni Hediel", ar: "تيرنى بنى هديل" },
    { fr: "Bensekrane", ar: "بن سكران" },
    { fr: "Ain Nehala", ar: "عين النحالة" },
    { fr: "Hennaya", ar: "الحناية" },
    { fr: "Maghnia", ar: "مغنية" },
    { fr: "Hammam Boughrara", ar: "حمام بوغرارة" },
    { fr: "Souahlia", ar: "السواحلية" },
    { fr: "Msirda Fouaga", ar: "مسيردة الفواقة" },
    { fr: "Ain Fatah", ar: "عين فتاح" },
    { fr: "Souk Tleta", ar: "سوق الثالثاء" },
    { fr: "Sidi Abdelli", ar: "سيدي عبد اللى" },
    { fr: "Sebdou", ar: "سبدو" },
    { fr: "Beni Ouarsous", ar: "بني وارسوس" },
    { fr: "Sidi Medjahed", ar: "سيدي مجاهد" },
    { fr: "Beni Boussaid", ar: "بنى بوسعيد" },
    { fr: "Marsa Ben Mhidi", ar: "مرسى بن مهيدي" },
    { fr: "Nedroma", ar: "ندرومة" },
    { fr: "Beni Bahdel", ar: "بنى بهدل" },
    { fr: "Honaine", ar: "هنين" },
    { fr: "Tianet", ar: "تيانت" },
    { fr: "Ouled Riyah", ar: "أوالد رياح" },
    { fr: "Bouhlou", ar: "بوحلو" },
    { fr: "Beni Khellad", ar: "بني خالد" },
    { fr: "Ain Ghoraba", ar: "عين غرابة" },
    { fr: "Chetouane", ar: "شتوان" },
    { fr: "Mansourah", ar: "منصورة" },
    { fr: "Beni Semiel", ar: "بني صميل" },
    { fr: "Ain Kebira", ar: "عين الكبيرة" },
  ],
  "14": [
    { fr: "Tiaret", ar: "تيارت" },
    { fr: "Medroussa", ar: "مدروسة" },
    { fr: "Ain Bouchekif", ar: "عين بوشقيف" },
    { fr: "Sidi Ali Mellal", ar: "سيدي علي مالل" },
    { fr: "Ain Zarit", ar: "عين دزاريت" },
    { fr: "Ain Deheb", ar: "عين الذهب" },
    { fr: "Sidi Bakhti", ar: "سيدي بختي" },
    { fr: "Medrissa", ar: "مدريسة" },
    { fr: "Madna", ar: "مادنة" },
    { fr: "El Sebt", ar: "السبت" },
    { fr: "Mellakou", ar: "مالكو" },
    { fr: "Dahmouni", ar: "دحمونى" },
    { fr: "Rahouia", ar: "رحوية" },
    { fr: "Mahdia", ar: "مهدية" },
    { fr: "Sougueur", ar: "السوقر" },
    { fr: "Si Abdelghani", ar: "سي عبد الغنى" },
    { fr: "Ain El Hadid", ar: "الحديد عين" },
    { fr: "Djebilet Rosfa", ar: "جبيلة الرصفاء" },
    { fr: "El Naima", ar: "النعيمة" },
    { fr: "Meghila", ar: "مغيلة" },
    { fr: "Guertoufa", ar: "قرطوفة" },
    { fr: "Sidi Hosni", ar: "سيدي الحسني" },
    { fr: "Djilali Ben Amar", ar: "جياللي بن عمار" },
    { fr: "Sebaine", ar: "سبعين" },
    { fr: "Tousnina", ar: "توسنينة" },
    { fr: "Frenda", ar: "فرندة" },
    { fr: "Ain Kermes", ar: "عين كرمس" },
    { fr: "El Nadorah", ar: "الناظورة" },
    { fr: "Tagdemt", ar: "تاقدمت" },
    { fr: "Oued Lili", ar: "وادى ليلى" },
    { fr: "Mechraa Sfa", ar: "مشرع الصفا" },
    { fr: "Chehaima", ar: "شحيمة" },
    { fr: "Takhemaret", ar: "تاخمرت" },
    { fr: "Sidi Abderahmane", ar: "سيدي عبد الرحمان" },
    { fr: "El Faidja", ar: "الفايجة" },
    { fr: "Tidda", ar: "تيدة" },
  ],
  "15": [
    { fr: "Tizi Ouzou", ar: "تيزي وزو" },
    { fr: "Ain El Hammam", ar: "الحمام عين" },
    { fr: "Akbil", ar: "اقبيل" },
    { fr: "Freha", ar: "فريحة" },
    { fr: "Souamaa", ar: "سوامع" },
    { fr: "Mechtrass", ar: "مشطراس" },
    { fr: "Irdjen", ar: "ايرجن" },
    { fr: "Timizart", ar: "تيميزارت" },
    { fr: "Makouda", ar: "ماكودة" },
    { fr: "Draa El Mizan", ar: "الميزان ذراع" },
    { fr: "Tizi Ghennif", ar: "تيزى غنيف" },
    { fr: "Bounouh", ar: "بونوح" },
    { fr: "Ait Chaffaa", ar: "آيت شافع" },
    { fr: "Frikat", ar: "فريقات" },
    { fr: "Beni Aissi", ar: "بنى عيسى" },
    { fr: "Beni Zmenzer", ar: "بنى زمنزر" },
    { fr: "Iferhounene", ar: "ايفرحونن" },
    { fr: "Azazga", ar: "عزازقة" },
    { fr: "Iloula Oumalou", ar: "ايلولة أوما لو" },
    { fr: "Yakourene", ar: "إعكورن" },
    { fr: "Larbaa Nath Irathene", ar: "االربعاء ناث ايراثن" },
    { fr: "Tizi Rached", ar: "تيزى راشد" },
    { fr: "Zekri", ar: "زكرى" },
    { fr: "Ouaguenoun", ar: "وا قنون" },
    { fr: "Ain Zaouia", ar: "عين الزاوية" },
    { fr: "M'Kira", ar: "مكيرة" },
    { fr: "Ait Yahia", ar: "آيت يحيى" },
    { fr: "Ait Mahmoud", ar: "آيت محمود" },
    { fr: "El Maatka", ar: "المعاتقة" },
    { fr: "Ait Boumahdi", ar: "آيت بومهدى" },
    { fr: "Abi Youcef", ar: "أبى يوسف" },
    { fr: "Beni Douala", ar: "بنى دوالة" },
    { fr: "Illilten", ar: "إليلتن" },
    { fr: "Bouzguene", ar: "بوزقن" },
    { fr: "Ait Agouacha", ar: "آيت عقواشة" },
    { fr: "Ouadhia", ar: "واضية" },
    { fr: "Azzefoun", ar: "أزفون" },
    { fr: "Tigzirt", ar: "تقزيرت" },
    { fr: "Ait Aissa Mimoun", ar: "ايت عيسى ميمون" },
    { fr: "Boghni", ar: "بوغنى" },
    { fr: "Ifigha", ar: "ايفيغاء" },
    { fr: "Ait Oumalou", ar: "آيت أومالو" },
    { fr: "Tirmitine", ar: "تيرمتين" },
    { fr: "Akerrou", ar: "أقرو" },
    { fr: "Yatafene", ar: "يطافن" },
    { fr: "Beni Ziki", ar: "بنى زيكى" },
    { fr: "Ben Kheda Draa", ar: "ذراع بن خدة" },
    { fr: "Ouacif", ar: "واسيف" },
    { fr: "Idjeur", ar: "إيجر" },
    { fr: "Mekla", ar: "مقلع" },
    { fr: "Tizi N'Tleta", ar: "نثالثة تيزى" },
    { fr: "Beni Yenni", ar: "بنى ينى" },
    { fr: "Aghrib", ar: "أغريب" },
    { fr: "Iflissen", ar: "افليسن" },
    { fr: "Boudjima", ar: "بوجيمة" },
    { fr: "Ait Yahia Moussa", ar: "آيت يحى موسى" },
    { fr: "Souk El Tenine", ar: "سوق االثنين" },
    { fr: "Ait Khellili", ar: "آيت خليلي" },
    { fr: "Sidi Naamane", ar: "سيدي نعمان" },
    { fr: "Iboudrarene", ar: "إبودرارن" },
    { fr: "Agouni Gueghrane", ar: "آقنى قغران" },
    { fr: "Mizrana", ar: "مزرانة" },
    { fr: "Imsouhal", ar: "إمسوحال" },
    { fr: "Tadmait", ar: "تادمايت" },
    { fr: "Ait Bouadou", ar: "آيت بوعدو" },
    { fr: "Assi Youcef", ar: "أسى يوسف" },
    { fr: "Ait Toudert", ar: "آيت تودرت" },
  ],
  "16": [
    { fr: "Alger Centre", ar: "الجزائر الوسطى" },
    { fr: "Sidi M'Hamed", ar: "سيدي امحمد" },
    { fr: "El Madania", ar: "المدنية" },
    { fr: "Belouizdad Mohamed", ar: "محمد بلوزداد" },
    { fr: "Bab El Oued", ar: "باب الوادي" },
    { fr: "Bologhine Ibn Ziri", ar: "بولوغين إبن زيري" },
    { fr: "El Casbah", ar: "القصبة" },
    { fr: "Oued Koriche", ar: "وادي قريش" },
    { fr: "Bir Mourad Rais", ar: "بئر مراد رايس" },
    { fr: "El Biar", ar: "األبيار" },
    { fr: "Bouzareah", ar: "بوزريعة" },
    { fr: "Birkhadem", ar: "بئر خادم" },
    { fr: "El Harrach", ar: "الحراش" },
    { fr: "Baraki", ar: "براقي" },
    { fr: "Oued Smar", ar: "وادي سمار" },
    { fr: "Boubouba", ar: "بوروبة" },
    { fr: "Hussein Dey", ar: "حسين داي" },
    { fr: "El Kouba", ar: "القبة" },
    { fr: "Bachdjarah", ar: "باش جراح" },
    { fr: "Dar El Beida", ar: "الدار البيضاء" },
    { fr: "Bab Ezzouar", ar: "باب الزوار" },
    { fr: "Ben Aknoun", ar: "بن عكنون" },
    { fr: "Dely Brahim", ar: "دالي إبرهيم" },
    { fr: "El Hammamet", ar: "الحمامات" },
    { fr: "Rais Hamidou", ar: "الرايس حميدو" },
    { fr: "Djasr Kassentina", ar: "جسر قسنطينة" },
    { fr: "El Mouradia", ar: "المرادية" },
    { fr: "Hydra", ar: "حيدرة" },
    { fr: "El Mohammadia", ar: "المحمدية" },
    { fr: "Bordj El Kiffan", ar: "برج الكيفان" },
    { fr: "El Magharia", ar: "المغارية" },
    { fr: "Beni Messous", ar: "بني مسوس" },
    { fr: "Les Eucalyptus", ar: "الكليتوس" },
    { fr: "Birtouta", ar: "بئر توتة" },
    { fr: "Tessala El Merdja", ar: "تسالة المرجى" },
    { fr: "Ouled Chebel", ar: "أوالد الشبل" },
    { fr: "Sidi Moussa", ar: "سيدي موسى" },
    { fr: "Ain Taya", ar: "عين طاية" },
    { fr: "Bordj El Bahri", ar: "البحري برج" },
    { fr: "El Marsa", ar: "المرسى" },
    { fr: "El Haraoua", ar: "الهراوة" },
    { fr: "Rouiba", ar: "الرويبة" },
    { fr: "Reghaia", ar: "رغاية" },
    { fr: "Ain Benian", ar: "عين البنيان" },
    { fr: "Staoueli", ar: "سطاوالي" },
    { fr: "Zeralda", ar: "زرالدة" },
    { fr: "Mahelma", ar: "معالمة" },
    { fr: "El Rahmania", ar: "الرحمانية" },
    { fr: "Souidania", ar: "سويدانية" },
    { fr: "Cheraga", ar: "الشراقة" },
    { fr: "Ouled Fayet", ar: "أوالد فايت" },
    { fr: "El Achour", ar: "العاشور" },
    { fr: "Draria", ar: "درارية" },
    { fr: "Douera", ar: "الدويرة" },
    { fr: "Baba Hassan", ar: "بابا حسن" },
    { fr: "Khraicia", ar: "خرايسية" },
    { fr: "Saoula", ar: "السحاولة" },
  ],
  "17": [
    { fr: "Djelfa", ar: "الجلفة" },
    { fr: "Moudjebara", ar: "مجبارة" },
    { fr: "El Guedid", ar: "القديد" },
    { fr: "Hassi Bahbah", ar: "حاسي بحبح" },
    { fr: "Ain Maabed", ar: "عين معبد" },
    { fr: "Zaccar", ar: "زكار" },
    { fr: "Sidi Bayzid", ar: "سيدي بايزيد" },
    { fr: "El Mliliha", ar: "المليليحة" },
    { fr: "El Idrissia", ar: "االدريسية" },
    { fr: "Douis", ar: "دويس" },
    { fr: "Hassi El Euch", ar: "العش حاسى" },
    { fr: "Ain Chouhada", ar: "عين الشهداء" },
    { fr: "Dar Chioukh", ar: "دار الشيوخ" },
    { fr: "El Charef", ar: "الشارف" },
    { fr: "Beni Yagoub", ar: "بنى يعقوب" },
    { fr: "Zaafrane", ar: "زعفران" },
    { fr: "Ain El Ibel", ar: "االبل عين" },
    { fr: "Tadmit", ar: "تاعظميت" },
  ],
  "18": [
    { fr: "Jijel", ar: "جيجل" },
    { fr: "Erraguene", ar: "أرا قن" },
    { fr: "El Aouana", ar: "العوانة" },
    { fr: "Ziama Mansouria", ar: "زيامة منصورية" },
    { fr: "El Taher", ar: "الطاهير" },
    { fr: "Emir Abdelkader", ar: "االمير عبد القادر" },
    { fr: "Chekfa", ar: "الشقفة" },
    { fr: "El Chahana", ar: "الشحنة" },
    { fr: "El Milia", ar: "الميلية" },
    { fr: "Sidi Maarouf", ar: "سيدي معروف" },
    { fr: "Settara", ar: "السطارة" },
    { fr: "El Ancer", ar: "العنصر" },
    { fr: "Sidi Abdelaziz", ar: "سيدي عبد العزيز" },
    { fr: "Kaous", ar: "قاوس" },
    { fr: "Ghebala", ar: "غبالة" },
    { fr: "Bouraoui Belhadef", ar: "بوراوى بلهادف" },
    { fr: "Djmila", ar: "جيملة" },
    { fr: "Selma Benziada", ar: "سلمى بن زيادة" },
    { fr: "Boussif Ouled Askeur", ar: "بوسيف أوالد عسكر" },
    { fr: "El Kennar Nouchfi", ar: "نشفى القنار" },
    { fr: "Ouled Yahia Khadrouch", ar: "أوالد يحيى خدروش" },
    { fr: "Boudria Beni Yadjis", ar: "بودريعة بني ياجيس" },
    { fr: "Kheiri Oued Adjoul", ar: "خيري واد عجول" },
    { fr: "Texenna", ar: "تاكسنة" },
    { fr: "Djemaa Beni Habibi", ar: "الجمعة بنى حبيبى" },
    { fr: "Bordj Taher", ar: "برج الطهر" },
    { fr: "Ouled Rabah", ar: "أوالد رابح" },
    { fr: "Oudjana", ar: "وجانة" },
  ],
  "19": [
    { fr: "Setif", ar: "سطيف" },
    { fr: "Ain El Kebira", ar: "الكبيرة العين" },
    { fr: "Beni Aziz", ar: "بنى عزيز" },
    { fr: "Ouled Si Ahmed", ar: "أوالد سي أحمد" },
    { fr: "Boutaleb", ar: "بوطالب" },
    { fr: "Ain Roua", ar: "عين الروى" },
    { fr: "Draa Kebila", ar: "ذراع قبيلة" },
    { fr: "Bir El Arch", ar: "العرش بئر" },
    { fr: "Beni Chebana", ar: "بنى شبانة" },
    { fr: "Ouled Tebben", ar: "أوالد تبان" },
    { fr: "El Hamma", ar: "الحامة" },
    { fr: "Maaouia", ar: "معاوية" },
    { fr: "Ain Legradj", ar: "عين لقراج" },
    { fr: "Ain Abessa", ar: "عين عباسة" },
    { fr: "El Dehamcha", ar: "الدهامشة" },
    { fr: "Babor", ar: "بابور" },
    { fr: "Guidjel", ar: "قجال" },
    { fr: "Ain El Hadjar", ar: "الحجر عين" },
    { fr: "Bousselam", ar: "بوسالم" },
    { fr: "El Eulma", ar: "العلمة" },
    { fr: "Djemila", ar: "جميلة" },
    { fr: "Beni Ourtilane", ar: "بنى ورثيالن" },
    { fr: "El Rosfa", ar: "الرصفة" },
    { fr: "Ouled Adouane", ar: "أوالد عدوان" },
    { fr: "Belaa", ar: "بلعة" },
    { fr: "Ain Arnat", ar: "عين أرنات" },
    { fr: "Amoucha", ar: "عموشة" },
    { fr: "Ain Oulmene", ar: "عين أولمان" },
    { fr: "Bordj Beida", ar: "بيضاء برج" },
    { fr: "Bouandas", ar: "بوعنداس" },
    { fr: "Bazer Sakhra", ar: "بازر الصخرة" },
    { fr: "Hammam Soukhna", ar: "حمام السخنة" },
    { fr: "Mezloug", ar: "مزلوق" },
    { fr: "Bir Haddada", ar: "بئر حدادة" },
    { fr: "Serdj El Ghoul", ar: "الغول سرج" },
    { fr: "Harbil", ar: "حربيل" },
    { fr: "El Ouricia", ar: "األوريسية" },
    { fr: "Tizi N'Bechar", ar: "نبشار تيزى" },
    { fr: "Salah Bey", ar: "صالح باي" },
    { fr: "Ain Azel", ar: "عين ازال" },
    { fr: "Guenzet", ar: "قنزات" },
    { fr: "Tala Ifacene", ar: "تالة إيفاسن" },
    { fr: "Bougaa", ar: "بوقاعة" },
    { fr: "Beni Fouda", ar: "بنى فودة" },
    { fr: "Tachouda", ar: "تاشورة" },
    { fr: "Beni Mouhli", ar: "بنى موحلى" },
    { fr: "Ouled Sabor", ar: "أوالد صابر" },
    { fr: "Guellal", ar: "قالل" },
    { fr: "Ain Sebt", ar: "عين السبت" },
    { fr: "Hammam Guergour", ar: "حمام قرقور" },
    { fr: "Ait Noual M'Zada", ar: "مزادة نوال آيت" },
    { fr: "Ksar El Abtal", ar: "األبطال قصر" },
    { fr: "Beni Hocine", ar: "بنى حسين" },
    { fr: "Ait Tizi", ar: "آيت تيزي" },
    { fr: "Maoklane", ar: "ماوكالن" },
    { fr: "Guelta Zerga", ar: "القلتة الزرقاء" },
    { fr: "Oued El Bared", ar: "البارد وادي" },
    { fr: "El Taya", ar: "الطاية" },
    { fr: "El Ouldja", ar: "الولجة" },
    { fr: "El Tella", ar: "التلة" },
  ],
  "20": [
    { fr: "Saida", ar: "سعيدة" },
    { fr: "Doui Thabet", ar: "دوي ثابت" },
    { fr: "Ain Hadjar", ar: "عين الحجر" },
    { fr: "Ouled Khaled", ar: "أوالد خالد" },
    { fr: "Moulay Larbi", ar: "موالي العربي" },
    { fr: "Youb", ar: "يوب" },
    { fr: "Hounet", ar: "هونت" },
    { fr: "Sidi Amar", ar: "سيدي عمار" },
    { fr: "Sidi Boubekeur", ar: "سيدي بوبكر" },
    { fr: "El Hassassna", ar: "الحساسنة" },
    { fr: "El Maamora", ar: "المعمورة" },
    { fr: "Sidi Ahmed", ar: "سيدي أحمد" },
    { fr: "Ain Skhouna", ar: "العين السخونة" },
    { fr: "Ouled Brahim", ar: "أوالد ابراهيم" },
    { fr: "Tircine", ar: "تيرسين" },
    { fr: "Ain Soltane", ar: "عين السلطان" },
  ],
  "21": [
    { fr: "Skikda", ar: "سكيكدة" },
    { fr: "Ain Zouit", ar: "عين زويت" },
    { fr: "El Hadaiek", ar: "الحدائق" },
    { fr: "Azzaba", ar: "عزابة" },
    { fr: "Djendel Saadi Med", ar: "جندل سعدي محمد" },
    { fr: "Ain Cherchar", ar: "عين شرشار" },
    { fr: "Bekkouche Lakhdar", ar: "بكوش االخضر" },
    { fr: "Ben Azzouz", ar: "بن عزوز" },
    { fr: "Es Sebt", ar: "السبت" },
    { fr: "Collo", ar: "القل" },
    { fr: "Beni Zid", ar: "بنى زيد" },
    { fr: "Kerkera", ar: "الكركرة" },
    { fr: "Ouled Attia", ar: "أوالد عطية" },
    { fr: "Oued Zhour", ar: "وادى الزهور" },
    { fr: "El Zitouna", ar: "الزيتونة" },
    { fr: "El Harrouch", ar: "الحروش" },
    { fr: "Zardezas", ar: "زردازة" },
    { fr: "Ouled Hebaba", ar: "أوالد حبابة" },
    { fr: "Sidi Mezghiche", ar: "سيدي مزغيش" },
    { fr: "Emdjez Edchich", ar: "مجاز الدشيش" },
    { fr: "Beni Oulbane", ar: "بنى ولبان" },
    { fr: "Ain Bouziane", ar: "عين بوزيان" },
    { fr: "Ramdane Djamel", ar: "رمضان جمال" },
    { fr: "Beni Bachir", ar: "بنى بشير" },
    { fr: "Salah Bouchaour", ar: "صالح بو الشعور" },
    { fr: "Tamalous", ar: "تمالوس" },
    { fr: "Ain Kechera", ar: "عين قشرة" },
    { fr: "Oum Toub", ar: "أم الطوب" },
    { fr: "Bein El Ouiden", ar: "الويدان بين" },
    { fr: "Filfila", ar: "فلفلة" },
    { fr: "El Cheraia", ar: "الشرايع" },
    { fr: "Kanoua", ar: "قنواع" },
    { fr: "El Ghedir", ar: "الغدير" },
    { fr: "Bouchetata", ar: "بوشطاطة" },
    { fr: "Ouldja Boulbalout", ar: "الولجة بوالبلوط" },
    { fr: "Khenak Mayoun", ar: "خناق مايون" },
    { fr: "Hamadi Krouma", ar: "حمادى كرومة" },
    { fr: "El Marsa", ar: "المرسى" },
  ],
  "22": [
    { fr: "Sidi Bel Abbes", ar: "سيدي بلعباس" },
    { fr: "Tessala", ar: "تسالة" },
    { fr: "Sidi Brahim", ar: "سيدي ابراهيم" },
    { fr: "Mostefa Ben Brahim", ar: "مصطفى بن ابراهيم" },
    { fr: "Telagh", ar: "تالغ" },
    { fr: "Mezaourou", ar: "مزاورو" },
    { fr: "Boukhanifis", ar: "بو خنفيس" },
    { fr: "Sidi Ali Boussidi", ar: "سيدي على بوسيدى" },
    { fr: "Badredine Mokrani", ar: "بدر الدين المقرانى" },
    { fr: "Marhoum", ar: "مرحوم" },
    { fr: "Tafissour", ar: "تفسور" },
    { fr: "El Amarnas", ar: "العمارنة" },
    { fr: "Tilmouni", ar: "تلمونى" },
    { fr: "Sidi Lahcene", ar: "سيدي لحسن" },
    { fr: "Ain Trid", ar: "عين الثريد" },
    { fr: "Makedra", ar: "مقدرة" },
    { fr: "Tenira", ar: "تنبرة" },
    { fr: "Moulay Slissen", ar: "موالى سليسن" },
    { fr: "El Hacaiba", ar: "الحصيبة" },
    { fr: "Hassi Zahana", ar: "حاسى زهانة" },
    { fr: "Tabia", ar: "طابية" },
    { fr: "Merine", ar: "مرين" },
    { fr: "Ras El Ma", ar: "الماء رأس" },
    { fr: "Ain Tindamine", ar: "عين تندمين" },
    { fr: "Ain Kada", ar: "عين قادة" },
    { fr: "M'Cid", ar: "مسيد" },
    { fr: "Sidi Khaled", ar: "سيدي خالد" },
    { fr: "Ain El Berd", ar: "البرد عين" },
    { fr: "Sfisef", ar: "سفيزف" },
    { fr: "Ain Adden", ar: "عين أدن" },
    { fr: "Oued Taourira", ar: "وادى تاوريرة" },
    { fr: "El Dhaya", ar: "الضاية" },
    { fr: "Zerouala", ar: "زروالة" },
    { fr: "Lamtar", ar: "لمطار" },
    { fr: "Sidi Chaib", ar: "سيدي شعيب" },
    { fr: "Sidi Daho de Zairs", ar: "الزاير دحو سيدي" },
    { fr: "Oued Sebaa", ar: "وادى السبع" },
    { fr: "Boudjebaa El Bordj", ar: "البرج بوجبهة" },
    { fr: "Sehala Thaoura", ar: "سهالة الثورة" },
    { fr: "Sidi Yacoub", ar: "سيدي يعقوب" },
    { fr: "Sidi Hamadouche", ar: "سيدي حمادوش" },
    { fr: "Belarbi", ar: "بلعربى" },
    { fr: "Oued Sefioun", ar: "وادى سفيون" },
    { fr: "Teghalimet", ar: "تغاليمت" },
    { fr: "Ben Badis", ar: "ابن باديس" },
    { fr: "Sidi Ali Benyoub", ar: "سيدي على بن يوب" },
    { fr: "Chetouane Belaila", ar: "شيطوان بليلة" },
    { fr: "Bir El Hammam", ar: "الحمام بئر" },
    { fr: "Taoudmout", ar: "تاودموت" },
    { fr: "Redjem Demouche", ar: "رجم دموش" },
    { fr: "Benachiba Chelia", ar: "بن عشيبة الشيلية" },
    { fr: "Hassi Daho", ar: "حاسى دحو" },
  ],
  "23": [
    { fr: "Annaba", ar: "عنابة" },
    { fr: "Berrahal", ar: "برحال" },
    { fr: "El Hadjar", ar: "الحجار" },
    { fr: "El Eulma", ar: "العلمة" },
    { fr: "El Bouni", ar: "البوني" },
    { fr: "Oued El Aneb", ar: "العنب وادي" },
    { fr: "Cheurfa", ar: "الشرفة" },
    { fr: "Seraidi", ar: "سرايدي" },
    { fr: "Ain Berda", ar: "عين الباردة" },
    { fr: "Chetaibi", ar: "شطايبي" },
    { fr: "Sidi Amar", ar: "سيدي عمار" },
    { fr: "El Treat", ar: "التريعات" },
  ],
  "24": [
    { fr: "Guelma", ar: "قالمة" },
    { fr: "Nechmaya", ar: "نشماية" },
    { fr: "Bouati Mahmoud", ar: "بوعاتي محمود" },
    { fr: "Oued Zenati", ar: "وادي الزناتي" },
    { fr: "Tamlouka", ar: "تاملوكة" },
    { fr: "Oued Fragha", ar: "وادي فراغة" },
    { fr: "Ain Sandel", ar: "عين صندل" },
    { fr: "Ras El Agba", ar: "العقبة راس" },
    { fr: "Dahouara", ar: "الدهوارة" },
    { fr: "Belkheir", ar: "بلخير" },
    { fr: "Ben Djarah", ar: "بن جراح" },
    { fr: "Bouhamdane", ar: "بوحمدان" },
    { fr: "Ain Makhlouf", ar: "عين مخلوف" },
    { fr: "Ain Ben Beida", ar: "عين بن بيضاء" },
    { fr: "El Khezaras", ar: "لخزارة" },
    { fr: "Beni Mezline", ar: "بنى مزلين" },
    { fr: "Bouhachana", ar: "بوحشانة" },
    { fr: "Guelaat Bou Sbaa", ar: "بوصبع قلعة" },
    { fr: "Hammam Debagh", ar: "حمام دباغ" },
    { fr: "El Fedjoudj", ar: "الفجوج" },
    { fr: "Bordj Sabat", ar: "برج صباط" },
    { fr: "Hammam N'Bail", ar: "النبايل حمام" },
    { fr: "Ain Larbi", ar: "عين العربى" },
    { fr: "Medjez Amar", ar: "مجاز عمار" },
    { fr: "Bouchegouf", ar: "بوشقوف" },
    { fr: "Heliopolis", ar: "هيليوبوليس" },
    { fr: "Houari Boumediene", ar: "هواري بومدين" },
    { fr: "El Roknia", ar: "الركنية" },
    { fr: "Sellaoua Announa", ar: "سالوة عنونة" },
    { fr: "Medjez Sfa", ar: "مجاز الصفاء" },
    { fr: "Boumahra Ahmed", ar: "بومهرة أحمد" },
    { fr: "Ain Reggada", ar: "عين رقادة" },
    { fr: "Oued Cheham", ar: "وادى الشحم" },
    { fr: "Djeballah Khemissi", ar: "جبالة الخميسى" },
  ],
  "25": [
    { fr: "Constantine", ar: "قسنطينة" },
    { fr: "Hamma Bouziane", ar: "حامة بوزيان" },
    { fr: "Ibn Badis", ar: "ابن باديس الهرية" },
    { fr: "Zighout Youcef", ar: "زيغود يوسف" },
    { fr: "Didouche Mourad", ar: "ديدوش مراد" },
    { fr: "El Khroub", ar: "الخروب" },
    { fr: "Ain Abid", ar: "عين عبيد" },
    { fr: "Beni Hamidene", ar: "بنى حميدان" },
    { fr: "Ouled Rahmoune", ar: "أوالد رحمون" },
    { fr: "Ain Smara", ar: "عين سمارة" },
    { fr: "Messaoud Boujeriou", ar: "مسعود بوجريو" },
    { fr: "Ibn Ziad", ar: "ابن زياد" },
  ],
  "26": [
    { fr: "Medea", ar: "المدية" },
    { fr: "Ouzera", ar: "وزرة" },
    { fr: "Ouled Maaref", ar: "أوالد معرف" },
    { fr: "El Aissaouia", ar: "العيساوية" },
    { fr: "Ouled Deid", ar: "اوالد دايد" },
    { fr: "El Omaria", ar: "العمارية" },
    { fr: "Derrag", ar: "دراق" },
    { fr: "El Guelb El Kebir", ar: "الكبير القلب" },
    { fr: "Mezghana", ar: "مزغنة" },
    { fr: "Ouled Brahim", ar: "أوالد ابراهيم" },
    { fr: "Tizi Mahdi", ar: "تيزي مهدي" },
    { fr: "Sidi Ziane", ar: "سيدي زيان" },
    { fr: "Tamesguida", ar: "تامسقيدة" },
    { fr: "El Hamdania", ar: "الحمدانية" },
    { fr: "Bouskene", ar: "بوسكن" },
    { fr: "El Rebaia", ar: "الربعية" },
    { fr: "Bouchrahil", ar: "بوشراحيل" },
    { fr: "Baata", ar: "بعطة" },
    { fr: "Sidi Naamane", ar: "سيدي نعمان" },
    { fr: "Ouled Bouachra", ar: "أوالد بوعشرة" },
    { fr: "Sidi Zahar", ar: "سيدي زهار" },
    { fr: "Oued Harbil", ar: "وادى حربيل" },
    { fr: "Ben Chicao", ar: "بن شكاو" },
    { fr: "Sidi Damed", ar: "سيدى دامد" },
    { fr: "Souagui", ar: "السواقى" },
    { fr: "El Zoubiria", ar: "الزبيرية" },
    { fr: "El Azizia", ar: "العزيزية" },
    { fr: "Djouab", ar: "جواب" },
    { fr: "Meghraoua", ar: "مغراوة" },
    { fr: "Ouamri", ar: "عوامرى" },
    { fr: "Si Mahdjoub", ar: "سى المحجوب" },
    { fr: "Tlatet Eddouair", ar: "ثالثة دوائر" },
    { fr: "Beni Slimane", ar: "بنى سليمان" },
    { fr: "Berrouaghia", ar: "البرواقية" },
    { fr: "Seghouane", ar: "سغوان" },
    { fr: "Mfatha", ar: "مفاتحة" },
    { fr: "Mihoub", ar: "ميهوب" },
    { fr: "Tablat", ar: "تابالط" },
    { fr: "Deux Bassins", ar: "الحوضان" },
    { fr: "Draa Essamar", ar: "ذراع السمار" },
    { fr: "Sidi Errabie", ar: "سيدي الربيع" },
    { fr: "Bir Ben Abed", ar: "بئر بن عابد" },
    { fr: "El Ouinet", ar: "العوينات" },
    { fr: "Bouaichoun", ar: "بوعيشون" },
    { fr: "Hannacha", ar: "حناشة" },
    { fr: "Sedraia", ar: "صدراية" },
    { fr: "Medjebar", ar: "مجبر" },
    { fr: "Khams Djouamaa", ar: "خمس جوامع" },
  ],
  "27": [
    { fr: "Mostaganem", ar: "مستغانم" },
    { fr: "Sayada", ar: "صيادة" },
    { fr: "Fornaka", ar: "فرناكة" },
    { fr: "Stidia", ar: "ستيدية" },
    { fr: "Ain Nouissy", ar: "عين نويسى" },
    { fr: "Hassi Maameche", ar: "حاسى ماماش" },
    { fr: "Ain Tadles", ar: "عين تادلس" },
    { fr: "Sour", ar: "سور" },
    { fr: "Oued El Kheir", ar: "الخير وادى" },
    { fr: "Sidi Belattar", ar: "سيدي بلعطار" },
    { fr: "Kheiredine", ar: "خير الدين" },
    { fr: "Sidi Ali", ar: "سيدي على" },
    { fr: "Abdelmalek Ramdane", ar: "عبد المالك رمضان" },
    { fr: "Hadjadj", ar: "حجاج" },
    { fr: "Nekmaria", ar: "نكمارية" },
    { fr: "Sidi Lakhdar", ar: "سيدي لخضر" },
    { fr: "Achaacha", ar: "عشعاشة" },
    { fr: "Khadra", ar: "خضراء" },
    { fr: "Bouguirat", ar: "بوقيراط" },
    { fr: "Sirat", ar: "سيرات" },
    { fr: "Ain Sidi Cherif", ar: "عين سيدي الشريف" },
    { fr: "El Mesra", ar: "ماسرة" },
    { fr: "Mansourah", ar: "منصورة" },
    { fr: "Souaflia", ar: "السوافلية" },
    { fr: "Ouled Boughalem", ar: "أوالد بوغالم" },
    { fr: "Ouled Maallah", ar: "أوالد مع هللا" },
    { fr: "Mezghrane", ar: "مزغران" },
    { fr: "Ain Boudinar", ar: "عين بودينار" },
    { fr: "Tazgait", ar: "تزقايت" },
    { fr: "Safsaf", ar: "صفصاف" },
    { fr: "El Touahria", ar: "الطواهرية" },
    { fr: "El Hassiane", ar: "الحسيان" },
  ],
  "28": [
    { fr: "M'Sila", ar: "المسيلة" },
    { fr: "El Maadid", ar: "المعاضيد" },
    { fr: "Hammam Dhalaa", ar: "حمام الضلعة" },
    { fr: "Ouled Derradj", ar: "أوالد دراج" },
    { fr: "Tarmount", ar: "تارمونت" },
    { fr: "El Mtarfa", ar: "المطارفة" },
    { fr: "Chellal", ar: "شالل" },
    { fr: "Ouled Mahdi", ar: "أوالد ماضى" },
    { fr: "Magra", ar: "مقرة" },
    { fr: "Berhoum", ar: "برهوم" },
    { fr: "Ain Khadra", ar: "عين خضراء" },
    { fr: "Ouled Addi Guebala", ar: "أوالد عدي لقبالة" },
    { fr: "Belaiba", ar: "بلعايبة" },
    { fr: "Sidi Aissa", ar: "سيدي عيسى" },
    { fr: "Ain El Hadjel", ar: "الحجل عين" },
    { fr: "Sidi Hadjeres", ar: "سيدي هجرس" },
    { fr: "Ouanougha", ar: "ونوغة" },
    { fr: "Ouled Sidi Brahim", ar: "أوالد سيدي ابراهيم" },
    { fr: "Maarif", ar: "معاريف" },
    { fr: "Dehahna", ar: "دهاهنة" },
    { fr: "Bouti Sayah", ar: "بوطى السايح" },
    { fr: "Khettouti Ced El Djir", ar: "الجير سد خطوطي" },
    { fr: "Souamaa", ar: "السوامع" },
    { fr: "Slim", ar: "سليم" },
    { fr: "Beni Ilmane", ar: "بنى يلمان" },
  ],
  "29": [
    { fr: "Mascara", ar: "معسكر" },
    { fr: "Bouhanifia", ar: "بوحنيفية" },
    { fr: "Tizi", ar: "تيزي" },
    { fr: "Hacine", ar: "حسين" },
    { fr: "Maoussa", ar: "ماوسة" },
    { fr: "Tighennif", ar: "تيغنيف" },
    { fr: "El Hachem", ar: "الحشم" },
    { fr: "Sidi Kada", ar: "سيدي قادة" },
    { fr: "Zelamta", ar: "زالمطة" },
    { fr: "Oued El Abtal", ar: "واد االبطال" },
    { fr: "Ain Ferah", ar: "عين فراح" },
    { fr: "Ghriss", ar: "غريس" },
    { fr: "Froha", ar: "فروحة" },
    { fr: "Matemore", ar: "مطمور" },
    { fr: "Makdha", ar: "ماقضة" },
    { fr: "Sidi Boussaid", ar: "سيدي بوسعيد" },
    { fr: "El Bordj", ar: "البرج" },
    { fr: "Ain Fekan", ar: "عين فكان" },
    { fr: "Benian", ar: "بنيان" },
    { fr: "Khalouia", ar: "خلوية" },
    { fr: "El Menaouer", ar: "المنور" },
    { fr: "Oued Taria", ar: "واد التاغية" },
    { fr: "Aouf", ar: "عوف" },
    { fr: "Ain Fares", ar: "عين فارس" },
    { fr: "Ain Frass", ar: "عين أفرص" },
    { fr: "Sig", ar: "سيق" },
    { fr: "Oggaz", ar: "عقاز" },
    { fr: "El Alaimia", ar: "العاليمية" },
    { fr: "El Gaada", ar: "القعدة" },
    { fr: "Zahana", ar: "زهانة" },
    { fr: "El Mohammadia", ar: "المحمدية" },
    { fr: "Sidi Abdelmoumene", ar: "سيدي عبد المومن" },
    { fr: "Ferraguig", ar: "فراقيق" },
    { fr: "El Ghomri", ar: "الغمري" },
    { fr: "Sedjerara", ar: "سجرارة" },
    { fr: "Mocta Douz", ar: "مقطع الدوز" },
    { fr: "Bou Henni", ar: "بوهني" },
    { fr: "El Guetna", ar: "القيطنة" },
    { fr: "El Mamounia", ar: "المامونية" },
    { fr: "El Keurt", ar: "الكرط" },
    { fr: "Gharrous", ar: "غروس" },
    { fr: "Guerdjoum", ar: "غرجوم" },
    { fr: "Chorfa", ar: "شرفة" },
    { fr: "Ras Ain Amirouche", ar: "راس عين عميروش" },
    { fr: "Nesmoth", ar: "نسمط" },
    { fr: "Sidi Abdeldjebar", ar: "سيدي عبد الجيار" },
    { fr: "El Sehailia", ar: "السهايلية" },
  ],
  "30": [
    { fr: "Ouargla", ar: "ورقلة" },
    { fr: "Ain Beida", ar: "عين البيضاء" },
    { fr: "N'Goussa", ar: "نقوسة" },
    { fr: "Hassi Messaoud", ar: "حاسى مسعود" },
    { fr: "Rouissat", ar: "الرويسات" },
    { fr: "Sidi Khouiled", ar: "سيدي خويلد" },
    { fr: "Hassi Ben Abdellah", ar: "حاسي بن عبد هللا" },
    { fr: "El Borma", ar: "البرمة" },
  ],
  "31": [
    { fr: "Oran", ar: "وهران" },
    { fr: "Gdyel", ar: "قديل" },
    { fr: "Bir El Djir", ar: "بئر الجير" },
    { fr: "Hassi Bounif", ar: "حاسي بونيف" },
    { fr: "Es Senia", ar: "السانية" },
    { fr: "Arzew", ar: "أرزيو" },
    { fr: "Bethioua", ar: "بطيوة" },
    { fr: "Marsat El Hadjadj", ar: "مرسى الحجاج" },
    { fr: "Ain El Turk", ar: "عين الترك" },
    { fr: "El Ancor", ar: "العنصر" },
    { fr: "Oued Tlelat", ar: "وادى تليالت" },
    { fr: "Tafraoui", ar: "طفراوى" },
    { fr: "Sidi Chami", ar: "سيدي الشحمى" },
    { fr: "Boufatis", ar: "بوفاتيس" },
    { fr: "Mers El Kebir", ar: "المرسى الكبير" },
    { fr: "Bousfer", ar: "بوصفر" },
    { fr: "El Kerma", ar: "الكرمة" },
    { fr: "El Braya", ar: "البراية" },
    { fr: "Hassi Ben Okba", ar: "حاسى بن عقبة" },
    { fr: "Ben Freha", ar: "بن فريحة" },
    { fr: "Hassi Mefsoukh", ar: "حاسى مفسوخ" },
    { fr: "Sidi Ben Yabka", ar: "سيدي بن يبقى" },
    { fr: "Messerghin", ar: "مسرغين" },
    { fr: "Boutlelis", ar: "بوتليليس" },
    { fr: "Ain El Kerma", ar: "عين الكرمة" },
    { fr: "Ain El Biya", ar: "عين البية" },
  ],
  "32": [
    { fr: "El Bayadh", ar: "البيض" },
    { fr: "Rogassa", ar: "رقاصة" },
    { fr: "Stitten", ar: "ستيتن" },
    { fr: "Brezina", ar: "بريزينة" },
    { fr: "Ghassoul", ar: "الغاسول" },
    { fr: "Boualem", ar: "بوعالم" },
    { fr: "Bougtoub", ar: "بوقطب" },
    { fr: "El Kheiter", ar: "الخيثر" },
    { fr: "Kef El Ahmar", ar: "كاف الاحمر" },
    { fr: "Kerakda", ar: "كراكدة" },
    { fr: "El Bnoud", ar: "البنود" },
    { fr: "Cheguig", ar: "الشقيق" },
    { fr: "Sidi Ameur", ar: "سيدي عمر" },
    { fr: "Tousmouline", ar: "توسمولين" },
    { fr: "Sidi Slimane", ar: "سيدي سليمان" },
    { fr: "Sidi Tifour", ar: "سيدي طيفور" },
  ],
  "33": [
    { fr: "Illizi", ar: "ايليزى" },
    { fr: "Debdeb", ar: "دبداب" },
    { fr: "Bordj Omar Driss", ar: "برج عمر ادريس" },
    { fr: "In Amenas", ar: "ان أميناس" },
  ],
  "34": [
    { fr: "Bordj Bou Arreridj", ar: "برج بوعريرج" },
    { fr: "Ras El Oued", ar: "راس الواد" },
    { fr: "Bordj Zemoura", ar: "برج زمورة" },
    { fr: "El Mansoura", ar: "المنصورة" },
    { fr: "El M'Hir", ar: "المهير" },
    { fr: "Ben Daoud", ar: "بن داود" },
    { fr: "El Achir", ar: "اليشير" },
    { fr: "Ain Taghrout", ar: "عين تاغروت" },
    { fr: "Bordj Ghdir", ar: "برج غدير" },
    { fr: "Sidi Embarek", ar: "سيدي امبارك" },
    { fr: "El Hamadia", ar: "الحمادية" },
    { fr: "Belimour", ar: "بليمور" },
    { fr: "Medjana", ar: "مجانة" },
    { fr: "Teniet Ennasr", ar: "ثنية النصر" },
    { fr: "Djaafra", ar: "جعافرة" },
    { fr: "El Main", ar: "إلماين" },
    { fr: "Ouled Brahem", ar: "أوالد براهم" },
    { fr: "Ouled Dahmane", ar: "أوالد دحمان" },
    { fr: "Hasnaoua", ar: "حسناوة" },
    { fr: "Khelil", ar: "خليل" },
    { fr: "Taglait", ar: "تقلعيت" },
    { fr: "El Ksour", ar: "القصور" },
    { fr: "Ouled Sidi Brahim", ar: "أوالد سيدي براهيم" },
    { fr: "Tafreg", ar: "تفرق" },
    { fr: "El Colla", ar: "القلة" },
    { fr: "Tixter", ar: "تكستار" },
    { fr: "El Ach", ar: "العش" },
    { fr: "El Anseur", ar: "العناصر" },
    { fr: "Tesmart", ar: "تسامرت" },
    { fr: "Ain Tasra", ar: "عين تسرة" },
    { fr: "Bir Kasdali", ar: "بئر قاصد علي" },
    { fr: "Ghilassa", ar: "غيالسة" },
    { fr: "El Rabta", ar: "الرابطة" },
    { fr: "Haraza", ar: "حرازة" },
  ],
  "35": [
    { fr: "Boumerdes", ar: "بومرداس" },
    { fr: "Boudouaou", ar: "بودواو" },
    { fr: "Afir", ar: "أعفير" },
    { fr: "Bordj Menaiel", ar: "برج منايل" },
    { fr: "Baghlia", ar: "بغلية" },
    { fr: "Sidi Daoud", ar: "سيدي داود" },
    { fr: "Naciria", ar: "الناصرية" },
    { fr: "Djinet", ar: "جنات" },
    { fr: "Isser", ar: "يسر" },
    { fr: "Zemmouri", ar: "زموري" },
    { fr: "Si Mustapha", ar: "سي مصطفى" },
    { fr: "Tidjelabine", ar: "تيجالبين" },
    { fr: "Chaabet El Ameur", ar: "شعبة العامر" },
    { fr: "Thenia", ar: "الثنية" },
    { fr: "Timezrit", ar: "تمزريت" },
    { fr: "Corso", ar: "قورصو" },
    { fr: "Ouled Moussa", ar: "أوالد موسى" },
    { fr: "Larbatache", ar: "األربعطاش" },
    { fr: "Bouzegza Keddara", ar: "بوزقزة قدارة" },
    { fr: "Taourga", ar: "تاورقة" },
    { fr: "Ouled Aissa", ar: "أوالد عيسى" },
    { fr: "Benchoud", ar: "بن شود" },
    { fr: "Dellys", ar: "دلس" },
    { fr: "Ammal", ar: "عمال" },
    { fr: "Beni Amrane", ar: "بنى عمران" },
    { fr: "Souk El Had", ar: "الحد سوق" },
    { fr: "Boudouaou El Bahri", ar: "بودواو البحرى" },
    { fr: "Ouled Hedadj", ar: "أوالد هداج" },
    { fr: "Laghata", ar: "لقاطة" },
    { fr: "Hammadi", ar: "حمادى" },
    { fr: "Khemis El Khechna", ar: "خميس الخشنة" },
    { fr: "El Kharrouba", ar: "الخروبة" },
  ],
  "36": [
    { fr: "El Tarf", ar: "الطارف" },
    { fr: "Bouhadjar", ar: "بوحجار" },
    { fr: "Ben M'Hidi", ar: "بن مهيدى" },
    { fr: "Bougous", ar: "بوقوس" },
    { fr: "El Kala", ar: "القالة" },
    { fr: "Ain El Assel", ar: "العسل عين" },
    { fr: "El Aioun", ar: "العيون" },
    { fr: "Bouteldja", ar: "بوثلجة" },
    { fr: "Souarekh", ar: "السوارخ" },
    { fr: "Berrihane", ar: "بريحان" },
    { fr: "Lac des Oiseaux", ar: "بحيرة الطيور" },
    { fr: "Cheffia", ar: "الشافية" },
    { fr: "Drean", ar: "الذرعان" },
    { fr: "Chihani", ar: "شحانى" },
    { fr: "Chebaita Mokhtar", ar: "شبيطة مختار" },
    { fr: "Besbes", ar: "البسباس" },
    { fr: "Asfour", ar: "عصفور" },
    { fr: "Echatt", ar: "الشط" },
    { fr: "Zerizer", ar: "زريزر" },
    { fr: "El Zitouna", ar: "الزيتونة" },
    { fr: "Ain Kerma", ar: "عين الكرمة" },
    { fr: "Oued Zitoun", ar: "وادى الزيتون" },
    { fr: "Hammam Beni Salah", ar: "حمام بنى صالح" },
    { fr: "Raml Souk", ar: "رمل السوق" },
  ],
  "37": [
    { fr: "Tindouf", ar: "تندوف" },
    { fr: "Oum El Assel", ar: "العسل أم" },
  ],
  "38": [
    { fr: "Tissemsilt", ar: "تيسمسيلت" },
    { fr: "Bordj Bou Naama", ar: "برج بونعامة" },
    { fr: "Theniet El Had", ar: "ثنية الاحد" },
    { fr: "Lazharia", ar: "الازهرية" },
    { fr: "Beni Chaib", ar: "بنى شعيب" },
    { fr: "Lardjem", ar: "لرجام" },
    { fr: "Melaab", ar: "ملعب" },
    { fr: "Sidi Lantri", ar: "سيدي العنترى" },
    { fr: "Bordj Emir Aek", ar: "برج البرير عبد القادر" },
    { fr: "Laayoune", ar: "العيون" },
    { fr: "Khemisti", ar: "خميستى" },
    { fr: "Ouled Bessem", ar: "أوالد بسام" },
    { fr: "Ammari", ar: "عمارى" },
    { fr: "El Youssoufia", ar: "اليوسفية" },
    { fr: "Sidi Boutouchent", ar: "سيدي بوتوشنت" },
    { fr: "El Larbaa", ar: "الاربعاء" },
    { fr: "El Maacem", ar: "المعاصم" },
    { fr: "Sidi Abed", ar: "سيدي عابد" },
    { fr: "Tamellaht", ar: "تمالحت" },
    { fr: "Sidi Slimane", ar: "سيدي سليمان" },
    { fr: "Boucaid", ar: "بوقايد" },
    { fr: "Beni Lahcene", ar: "بنى لحسن" },
  ],
  "39": [
    { fr: "El Oued", ar: "الوادى" },
    { fr: "Robbah", ar: "رباح" },
    { fr: "Oued El Alenda", ar: "العلندة وادى" },
    { fr: "El Bayadha", ar: "البياضة" },
    { fr: "El Nakhla", ar: "النخلة" },
    { fr: "Guemar", ar: "قمار" },
    { fr: "Kouinine", ar: "كوينين" },
    { fr: "Reguiba", ar: "الرقيبة" },
    { fr: "Hamraia", ar: "حمراية" },
    { fr: "Taghzout", ar: "تاغزوت" },
    { fr: "El Debila", ar: "الدبيلة" },
    { fr: "Hassani Abdelkrim", ar: "حسانى عبد الكريم" },
    { fr: "Hassi Khelifa", ar: "حاسى خليفة" },
    { fr: "Taleb Larbi", ar: "طالب العربي" },
    { fr: "Douar El Ma", ar: "الماء دوار" },
    { fr: "Sidi Aoun", ar: "سيدي عون" },
    { fr: "El Trifaoui", ar: "الطريفاوى" },
    { fr: "El Magrane", ar: "المقرن" },
    { fr: "Ben Ghecha", ar: "بني قشة" },
    { fr: "Ourmas", ar: "ورماس" },
    { fr: "El Ogla", ar: "العقلة" },
    { fr: "Mih Ouensa", ar: "ميه ونسى" },
  ],
  "40": [
    { fr: "Khenchela", ar: "خنشلة" },
    { fr: "M'Toussa", ar: "متوسة" },
    { fr: "Kais", ar: "قايس" },
    { fr: "Baghai", ar: "بغاى" },
    { fr: "El Hamma", ar: "الحامة" },
    { fr: "Ain Touila", ar: "عين الطويلة" },
    { fr: "Taouzianet", ar: "تاوزيانت" },
    { fr: "Bouhmama", ar: "بوحمامة" },
    { fr: "El Oueldja", ar: "الولجة" },
    { fr: "El Remila", ar: "الرميلة" },
    { fr: "Chechar", ar: "ششار" },
    { fr: "Djellal", ar: "جالل" },
    { fr: "Babar", ar: "بابار" },
    { fr: "Tamsa", ar: "طامزة" },
    { fr: "Ensigha", ar: "انسيغة" },
    { fr: "Ouled Rechache", ar: "أوالد رشاش" },
    { fr: "El Mahmel", ar: "المحمل" },
    { fr: "El Msara", ar: "مصارة" },
    { fr: "Yabous", ar: "يابوس" },
    { fr: "Khirane", ar: "خيران" },
    { fr: "Chelia", ar: "شلية" },
  ],
  "41": [
    { fr: "Souk Ahras", ar: "سوق أهراس" },
    { fr: "Sedrata", ar: "سدراتة" },
    { fr: "El Hanancha", ar: "الحنانشة" },
    { fr: "El Mechroha", ar: "المشروحة" },
    { fr: "Ouled Driss", ar: "أوالد ادريس" },
    { fr: "Tiffech", ar: "تيفاش" },
    { fr: "Zaarouria", ar: "الزعرورية" },
    { fr: "Taoura", ar: "تاورة" },
    { fr: "Drea", ar: "الدريعة" },
    { fr: "El Haddada", ar: "الحدادة" },
    { fr: "El Kheddara", ar: "الخضارة" },
    { fr: "El Merahna", ar: "المراهنة" },
    { fr: "Ouled Moumen", ar: "أوالد مومن" },
    { fr: "Bir Bouhouche", ar: "بئر بوحوش" },
    { fr: "M'Daourouch", ar: "مداوروش" },
    { fr: "Oum El Adhaim", ar: "العظايم أم" },
    { fr: "Ain Zana", ar: "عين الزانة" },
    { fr: "Ain Soltane", ar: "عين سلطان" },
    { fr: "Ouillen", ar: "ويالن" },
    { fr: "Sidi Fredj", ar: "سيدي فرج" },
    { fr: "Safel El Ouiden", ar: "الويدان سافل" },
    { fr: "El Ragouba", ar: "الراقوبة" },
    { fr: "Khemissa", ar: "خميسة" },
    { fr: "Oued Kebrit", ar: "وادى الكبريت" },
    { fr: "Terraguelt", ar: "ترقالت" },
    { fr: "El Zouabi", ar: "الزوابى" },
  ],
  "42": [
    { fr: "Tipaza", ar: "تيبازة" },
    { fr: "Menaceur", ar: "مناصر" },
    { fr: "Larhat", ar: "الأرهاط" },
    { fr: "Douaouda", ar: "دواودة" },
    { fr: "Bourkika", ar: "بورقيقة" },
    { fr: "Khemisti", ar: "خميستي" },
    { fr: "Aghbal", ar: "أغبال" },
    { fr: "Hadjout", ar: "حجوط" },
    { fr: "Sidi Amar", ar: "سيدي عامر" },
    { fr: "Gouraya", ar: "قوراية" },
    { fr: "El Nador", ar: "الناظور" },
    { fr: "El Chaiba", ar: "الشعيبة" },
    { fr: "Ain Tagourait", ar: "عين تاقورايت" },
    { fr: "Cherchell", ar: "شرشال" },
    { fr: "Damous", ar: "الداموس" },
    { fr: "Merad", ar: "مراد" },
    { fr: "Fouka", ar: "فوكة" },
    { fr: "Bou Ismail", ar: "بواسماعيل" },
    { fr: "Ahmer El Ain", ar: "العين أحمر" },
    { fr: "Bouharoun", ar: "بوهارون" },
    { fr: "Sidi Ghiles", ar: "سيدي غيالس" },
    { fr: "Messelmoun", ar: "مسلمون" },
    { fr: "Sidi Rached", ar: "سيدي راشد" },
    { fr: "Kolea", ar: "القليعة" },
    { fr: "El Attatba", ar: "الحطاطبة" },
    { fr: "Sidi Semiane", ar: "سيدي سميان" },
    { fr: "Beni Milleuk", ar: "بني ميلك" },
    { fr: "Hadjret Ennous", ar: "حجرة النص" },
  ],
  "43": [
    { fr: "Mila", ar: "ميلة" },
    { fr: "Ferdjioua", ar: "فرجيوة" },
    { fr: "Chelghoum Laid", ar: "شلغوم العيد" },
    { fr: "Oued Athmania", ar: "وادي العثمانية" },
    { fr: "Ain Melouk", ar: "عين الملوك" },
    { fr: "El Telerghma", ar: "التالغمة" },
    { fr: "Oued Seguen", ar: "وادى سقان" },
    { fr: "Tadjenanet", ar: "تاجنانت" },
    { fr: "Benyahia Abderrahmane", ar: "بن يحي .ع. رحمان" },
    { fr: "Oued Endja", ar: "وادى النجاء" },
    { fr: "Ahmed Rachedi", ar: "أحمد راشدي" },
    { fr: "Ouled Khelouf", ar: "أوالد اخلوف" },
    { fr: "Tiberguent", ar: "تيبرقنت" },
    { fr: "Bouhatem", ar: "بوحاتم" },
    { fr: "Rouached", ar: "الرواشد" },
    { fr: "Tessala Lemtai", ar: "تسالة لمطاعي" },
    { fr: "Grarem Gouga", ar: "القرارم قوقة" },
    { fr: "Sidi Merouane", ar: "سيدي مروان" },
    { fr: "Tassadane Haddada", ar: "تسدان حدادة" },
    { fr: "Deradji Bousselah", ar: "دراجى بوصالح" },
    { fr: "Minar Zarza", ar: "مينار زارزة" },
    { fr: "Amira Arras", ar: "اعميرة اراس" },
    { fr: "Terrai Bainen", ar: "ترعى باينان" },
    { fr: "Hamala", ar: "حمالة" },
    { fr: "Ain Tinn", ar: "عين التين" },
    { fr: "El Mechira", ar: "المشيرة" },
    { fr: "Sidi Khelifa", ar: "سيدي خليفة" },
    { fr: "Zeghaia", ar: "زغاية" },
    { fr: "El Ayadi Barbes", ar: "العياضى برباس" },
    { fr: "Ain Beida Harriche", ar: "عين البيضاء احريش" },
    { fr: "Yahia Beni Guecha", ar: "يحيى بنى قشة" },
    { fr: "El Chigara", ar: "الشيقارة" },
  ],
  "44": [
    { fr: "Ain Defla", ar: "عين الدفلى" },
    { fr: "Miliana", ar: "مليانة" },
    { fr: "Boumedfaa", ar: "بومدفع" },
    { fr: "Khemis Miliana", ar: "خميس مليانة" },
    { fr: "Hammam Righa", ar: "حمام ريغة" },
    { fr: "Arib", ar: "عريب" },
    { fr: "Djelida", ar: "جليدة" },
    { fr: "El Amra", ar: "العامرة" },
    { fr: "Bourached", ar: "بوراشد" },
    { fr: "El Attaf", ar: "العطاف" },
    { fr: "El Abadia", ar: "العبادية" },
    { fr: "Djendel", ar: "جندل" },
    { fr: "Oued Cheurfa", ar: "وادى الشرفاء" },
    { fr: "Ain Lechiakh", ar: "عين االشياخ" },
    { fr: "Oued Djemaa", ar: "واد الجمعة" },
    { fr: "El Rouina", ar: "الروينة" },
    { fr: "Zeddine", ar: "زدين" },
    { fr: "El Hassania", ar: "الحسانية" },
    { fr: "Bir Ouled Khelifa", ar: "بئر أوالد خليفة" },
    { fr: "Ain Soltane", ar: "عين السلطان" },
    { fr: "Tarik Ibn Ziad", ar: "طارق بن زياد" },
    { fr: "Bordj Emir Khaled", ar: "برج الأمير خالد" },
    { fr: "Ain Torki", ar: "عين التركى" },
    { fr: "Sidi Lakhdar", ar: "سيدي الاخضر" },
    { fr: "Ben Allel", ar: "بن عالل" },
    { fr: "Ain Benian", ar: "عين البنيان" },
    { fr: "El Hoceinia", ar: "الحسينية" },
    { fr: "Barbouche", ar: "بربوش" },
    { fr: "Djemaa Ouled Cheikh", ar: "جمعة أوالد الشيخ" },
    { fr: "El Mekhatria", ar: "المخاطرية" },
    { fr: "Bathia", ar: "بطحية" },
    { fr: "Tacheta Zegagha", ar: "تاشتة زقاغة" },
    { fr: "Ain Bouyahia", ar: "عين بويحى" },
    { fr: "El Maine", ar: "الماين" },
    { fr: "Tiberkanine", ar: "تبركانين" },
    { fr: "Belaas", ar: "بلعاص" },
  ],
  "45": [
    { fr: "Naama", ar: "النعامة" },
    { fr: "Mecheria", ar: "مشرية" },
    { fr: "Ain Sefra", ar: "عين الصفراء" },
    { fr: "Tiout", ar: "تيوت" },
    { fr: "Sfissifa", ar: "سفيسيفة" },
    { fr: "Moghrar", ar: "مغرار" },
    { fr: "Assela", ar: "عسلة" },
    { fr: "Djenien Bourzeg", ar: "جنين بورزق" },
    { fr: "Ain Ben Khelil", ar: "عين بن خليل" },
    { fr: "Mekmen Ben Amar", ar: "مكمن بن عمار" },
    { fr: "El Kasdir", ar: "القصدير" },
    { fr: "El Biodh", ar: "البيوض" },
  ],
  "46": [
    { fr: "Ain Temouchent", ar: "عين تموشنت" },
    { fr: "Chaabet El Ham", ar: "شعبة اللحم" },
    { fr: "Ain Kihal", ar: "عين الكيحل" },
    { fr: "Hammam Bouhadjar", ar: "حمام بو حجر" },
    { fr: "Bouzedjar", ar: "بوزجار" },
    { fr: "Oued Berkeche", ar: "وادى برقش" },
    { fr: "Aghlal", ar: "أغالل" },
    { fr: "Terga", ar: "تارقة" },
    { fr: "Ain El Arbaa", ar: "عين الاربعاء" },
    { fr: "Tamzoura", ar: "تامزورة" },
    { fr: "Chentouf", ar: "شنتوف" },
    { fr: "Sidi Ben Adda", ar: "سيدي بن عدة" },
    { fr: "Aoubellil", ar: "عقب الليل" },
    { fr: "El Malah", ar: "المالح" },
    { fr: "Sidi Boumediene", ar: "سيدي بومدين" },
    { fr: "Oued Sebbah", ar: "وادى الصباح" },
    { fr: "Ouled Boudjemaa", ar: "أوالد بوجمعة" },
    { fr: "Ain Tolba", ar: "عين الطلبة" },
    { fr: "El Amria", ar: "العامرية" },
    { fr: "Hassi El Ghella", ar: "الغلة حاسى" },
    { fr: "El Hassassna", ar: "الحساسنة" },
    { fr: "Ouled Kihal", ar: "أوالد الكيحل" },
    { fr: "Beni Saf", ar: "بني صاف" },
    { fr: "Sidi Safi", ar: "سيدي الصافي" },
    { fr: "Oulhaca Gheraba", ar: "ولهاصة الغرابة" },
    { fr: "Sidi Ourrach", ar: "سيدي اورياش" },
    { fr: "Emir Abdelkader", ar: "الأمير عبد القادر" },
    { fr: "El Messaid", ar: "المساعيد" },
  ],
  "47": [
    { fr: "Ghardaia", ar: "غرداية" },
    { fr: "Dhayet Ben Dhaoua", ar: "ضاية بن ضحوة" },
    { fr: "Berriane", ar: "بريان" },
    { fr: "Metlili", ar: "متليلي" },
    { fr: "El Guerrara", ar: "القرارة" },
    { fr: "El Atteuf", ar: "العطف" },
    { fr: "Zelfana", ar: "زلفانة" },
    { fr: "Sebseb", ar: "سبسب" },
    { fr: "Bounoura", ar: "بونورة" },
    { fr: "El Mansoura", ar: "المنصورة" },
  ],
  "48": [
    { fr: "Relizane", ar: "غليزان" },
    { fr: "Oued Rhiou", ar: "وادى رهيو" },
    { fr: "Belaassel Bouzegza", ar: "بلعسل بوزقزة" },
    { fr: "Sidi Saada", ar: "سيدي سعادة" },
    { fr: "Ouled Aich", ar: "أوالد يعيش" },
    { fr: "Sidi Lazreg", ar: "سيدي لزرق" },
    { fr: "El H'Madna", ar: "الحمادنة" },
    { fr: "Sidi M'Hamed Ben Ali", ar: "سيدي امحمد بن علي" },
    { fr: "Mediouna", ar: "مديونة" },
    { fr: "Sidi Khettab", ar: "سيدي خطاب" },
    { fr: "Ammi Moussa", ar: "عمي موسى" },
    { fr: "Zemmoura", ar: "زمورة" },
    { fr: "Beni Dergoun", ar: "بني درقن" },
    { fr: "Djidiouia", ar: "جديوية" },
    { fr: "El Guettar", ar: "القطار" },
    { fr: "El Hamri", ar: "الحمري" },
    { fr: "El Matmar", ar: "المطمر" },
    { fr: "Sidi M'Hamed Benaouda", ar: "سيدي محمد بن عودة" },
    { fr: "Ain Tarek", ar: "عين طارق" },
    { fr: "Oued Essalem", ar: "وادى السالم" },
    { fr: "Ouarizane", ar: "واريزان" },
    { fr: "Mazouna", ar: "مازونة" },
    { fr: "El Kalaa", ar: "القلعة" },
    { fr: "Ain Rahma", ar: "عين الرحمة" },
    { fr: "Yellel", ar: "يلل" },
    { fr: "Oued El Djemaa", ar: "وادى الجمعة" },
    { fr: "Ramka", ar: "الرمكة" },
    { fr: "Mendes", ar: "منداس" },
    { fr: "Lahlef", ar: "لحالف" },
    { fr: "Beni Zentis", ar: "بني زنطيس" },
    { fr: "Souk El Had", ar: "الحد سوق" },
    { fr: "Dar Ben Abdellah", ar: "دار بن عبد هللا" },
    { fr: "El Hassi", ar: "الحاسى" },
    { fr: "Had Echkalla", ar: "حد الشكالة" },
    { fr: "Ben Daoud", ar: "بن داود" },
    { fr: "El Ouldja", ar: "الولجة" },
    { fr: "Merdja Sidi Abed", ar: "مرجة سيدي عابد" },
    { fr: "Ouled Sidi Mihoub", ar: "أوالد سيدي الميهوب" },
  ],
  "49": [
    { fr: "Timimoun", ar: "تيميمون" },
    { fr: "Charouine", ar: "شروين" },
    { fr: "Ksar Kaddour", ar: "قصر قدور" },
    { fr: "Ouled Said", ar: "أوالد سعيد" },
    { fr: "Tinerkouk", ar: "تينركوك" },
    { fr: "Deldoul", ar: "دلدول" },
    { fr: "El Metarfa", ar: "المطارفة" },
    { fr: "Aougrout", ar: "أوقروت" },
    { fr: "Talmine", ar: "طالمين" },
    { fr: "Ouled Aissa", ar: "أوالد عيسى" },
  ],
  "50": [
    { fr: "Bordj Badji Mokhtar", ar: "برج باجى مختار" },
    { fr: "Timiaouine", ar: "تيمياوين" },
  ],
  "51": [
    { fr: "Ouled Djellal", ar: "أوالد جالل" },
    { fr: "Ras El Miaad", ar: "رأس الميعاد" },
    { fr: "Besbes", ar: "البسباس" },
    { fr: "Sidi Khaled", ar: "سيدي خالد" },
    { fr: "Doucen", ar: "الدوسن" },
    { fr: "El Chaiba", ar: "الشعيبة" },
  ],
  "52": [
    { fr: "Beni Abbes", ar: "بنى عباس" },
    { fr: "Ouled Khodeir", ar: "أوالد خضير" },
    { fr: "Timoudi", ar: "تيمودى" },
    { fr: "Beni Ikhlef", ar: "بنى يخلف" },
    { fr: "Igli", ar: "أقلى" },
    { fr: "Tabelbala", ar: "تبلبلة" },
    { fr: "El Ouata", ar: "الوطاء" },
    { fr: "Kerzaz", ar: "كرزاز" },
    { fr: "Ksabi", ar: "قصابى" },
    { fr: "Tamtert", ar: "تامترت" },
  ],
  "53": [
    { fr: "In Salah", ar: "إن صالح" },
    { fr: "In Ghar", ar: "ان غار" },
    { fr: "Foggaret Ezzaouia", ar: "فقارة الزاوية" },
  ],
  "54": [
    { fr: "In Guezzam", ar: "إن قزام" },
    { fr: "Tin Zaouatine", ar: "تين زواتين" },
  ],
  "55": [
    { fr: "Touggourt", ar: "توقرت" },
    { fr: "Blidat Ameur", ar: "بليدة عامر" },
    { fr: "Tebesbest", ar: "تيبسبست" },
    { fr: "Nezla", ar: "نزلة" },
    { fr: "Zaouia El Abidia", ar: "زاوية العابدية" },
    { fr: "Sidi Slimane", ar: "سيدي سليمان" },
    { fr: "El Hadjira", ar: "الحجيرة" },
    { fr: "El Taibet", ar: "الطيبات" },
    { fr: "Tamacine", ar: "تماسين" },
    { fr: "Benaceur", ar: "بن ناصر" },
    { fr: "M'Naguar", ar: "المنقر" },
    { fr: "El Megarine", ar: "المقارين" },
    { fr: "El Allia", ar: "العالية" },
  ],
  "56": [
    { fr: "Djanet", ar: "جانت" },
    { fr: "Bordj El Haouasse", ar: "برج الحواس" },
  ],
  "57": [
    { fr: "El Megaier", ar: "المغير" },
    { fr: "Still", ar: "سطيل" },
    { fr: "M'Rara", ar: "مرارة" },
    { fr: "Sidi Khelil", ar: "سيدي خليل" },
    { fr: "Tendla", ar: "تندلة" },
    { fr: "Djamaa", ar: "جامعة" },
    { fr: "Oum Touyour", ar: "أم الطيور" },
    { fr: "Sidi Amrane", ar: "سيدي عمران" },
  ],
  "58": [
    { fr: "El Meniaa", ar: "المنيعة" },
    { fr: "Hassi Fehal", ar: "حاسي الفحل" },
    { fr: "Hassi El Gara", ar: "حاسي القارة" },
  ],
  "59": [
    { fr: "Gueltat Sidi Saad", ar: "قلتة سيدي سعد" },
    { fr: "Ain Sidi Ali", ar: "عين سيدي على" },
    { fr: "El Beidha", ar: "البيضاء" },
    { fr: "Brida", ar: "بريدة" },
    { fr: "El Ghicha", ar: "الغيشة" },
    { fr: "Hadj Mecheri", ar: "حاج مشري" },
    { fr: "Taouiala", ar: "تاويالة" },
    { fr: "Aflou", ar: "آفلو" },
    { fr: "Oued Morra", ar: "واد مرة" },
    { fr: "Oued M'Zi", ar: "مزي واد" },
    { fr: "Sidi Bouzid", ar: "سيدي بوزيد" },
  ],
  "60": [
    { fr: "Seggana", ar: "سقانة" },
    { fr: "Barika", ar: "بريكة" },
    { fr: "Djezzar", ar: "الجزار" },
    { fr: "Bitam", ar: "بيطام" },
    { fr: "Tilatou", ar: "تيالطو" },
    { fr: "Ichemoul", ar: "إشمول" },
    { fr: "Amdoukel", ar: "إمدوكل" },
    { fr: "Ouled Ammar", ar: "أوالد عمار" },
    { fr: "Azil Abdelkader", ar: "عزيل عبد القادر" },
  ],
  "61": [
    { fr: "Branis", ar: "البرانيس" },
    { fr: "El Kantara", ar: "القنطرة" },
    { fr: "Ain Zaatout", ar: "عين زعطوط" },
    { fr: "El Outaya", ar: "الوطاية" },
    { fr: "Djemorah", ar: "جمورة" },
  ],
  "62": [
    { fr: "Negrine", ar: "نقرين" },
    { fr: "Bir El Ater", ar: "بئر العاتر" },
    { fr: "El Ogla El Malha", ar: "المالحة العقلة" },
    { fr: "Ferkane", ar: "فركان" },
  ],
  "63": [
    { fr: "El Gor", ar: "القور" },
    { fr: "El Aricha", ar: "العريشة" },
    { fr: "Sidi Djillali", ar: "سيدي الجياللي" },
    { fr: "El Bouihi", ar: "البويهي" },
  ],
  "64": [
    { fr: "Zmalet Emir Aek", ar: "زمالة األمير عبد القادر" },
    { fr: "Ksar Chellala", ar: "قصر الشاللة" },
    { fr: "Rechaiga", ar: "الرشايقة" },
    { fr: "Hamadia", ar: "حمادية" },
    { fr: "Serghine", ar: "سرغين" },
    { fr: "Bougara", ar: "بوقرة" },
  ],
  "65": [
    { fr: "Ain Oussera", ar: "عين وسارة" },
    { fr: "Benhar", ar: "بن هار" },
    { fr: "Had Sahary", ar: "حد الصحارى" },
    { fr: "Guernini", ar: "قرنيني" },
    { fr: "Birine", ar: "بيرين" },
    { fr: "Bouira Lahdeb", ar: "بويرة األحدب" },
    { fr: "Sidi Laadjel", ar: "سيدي لعجال" },
    { fr: "Hassi Fedoul", ar: "حاسى فدول" },
    { fr: "Ain Fekka", ar: "عين فقه" },
    { fr: "El Khemis", ar: "الخميس" },
  ],
  "66": [
    { fr: "Messaad", ar: "مسعد" },
    { fr: "Guettara", ar: "قطارة" },
    { fr: "Selmana", ar: "سلمانة" },
    { fr: "Oum Ladham", ar: "أم العظام" },
    { fr: "Deldoul", ar: "دلدول" },
    { fr: "Sed Rahal", ar: "سد الرحال" },
    { fr: "Feidh El Botma", ar: "فيض البطمة" },
    { fr: "Amourah", ar: "عمورة" },
  ],
  "67": [
    { fr: "Ain Boucif", ar: "عين بوسيف" },
    { fr: "El Kef Lakhdar", ar: "الكاف االخضر" },
    { fr: "Chellalet El Adhaoura", ar: "العذاورة شاللة" },
    { fr: "Ouled Hellal", ar: "أوالد هالل" },
    { fr: "Boghar", ar: "بوغار" },
    { fr: "Aziz", ar: "عزيز" },
    { fr: "Ksar El Boukhari", ar: "قصر البخاري" },
    { fr: "El Chahbounia", ar: "الشهبونية" },
    { fr: "Cheniguel", ar: "شنيقل" },
    { fr: "Mfatha", ar: "مفاتحة" },
    { fr: "Boughzoul", ar: "بوغزول" },
    { fr: "Ouled Antar", ar: "أوالد عنتر" },
    { fr: "Saneg", ar: "سانق" },
    { fr: "Bouaiche", ar: "بوعيش" },
    { fr: "Tafraout", ar: "تفراوت" },
    { fr: "Ain Ouksir", ar: "عين القصير" },
    { fr: "Oum El Djalil", ar: "أم الجليل" },
  ],
  "68": [
    { fr: "Oulten", ar: "ولتام" },
    { fr: "Djebel Messaad", ar: "جبل مساعد" },
    { fr: "Sidi Ameur", ar: "سيدي عامر" },
    { fr: "Tamsa", ar: "تامسة" },
    { fr: "Ben Srour", ar: "بن سرور" },
    { fr: "Ouled Slimane", ar: "أوالد سليمان" },
    { fr: "El Houamed", ar: "الحوامد" },
    { fr: "El Hamel", ar: "الهامل" },
    { fr: "Ouled Mansour", ar: "أوالد منصور" },
    { fr: "Bousaada", ar: "بوسعادة" },
    { fr: "Ain El Melh", ar: "الملح عين" },
    { fr: "Zarzour", ar: "زرزور" },
    { fr: "Mohamed Boudiaf", ar: "محمد بوضياف" },
    { fr: "Benzouh", ar: "بن زوه" },
    { fr: "Bir Fodda", ar: "بئر فضة" },
    { fr: "Ain Fares", ar: "عين فارس" },
    { fr: "Khoubana", ar: "خبانة" },
    { fr: "M'Cif", ar: "مسيف" },
    { fr: "Ain Errich", ar: "عين الريش" },
    { fr: "El Menea", ar: "مناعة" },
    { fr: "Medjedel", ar: "مجدل" },
    { fr: "Sidi M'Hamed", ar: "سيدي محمد" },
  ],
  "69": [
    { fr: "El Abiodh Sidi Cheikh", ar: "الأبيض سيدي الشيخ" },
    { fr: "Ain El Orak", ar: "العراك عين" },
    { fr: "Arbaouet", ar: "أربوات" },
    { fr: "Boussemghoun", ar: "بوسمغون" },
    { fr: "Chellala", ar: "شاللة" },
    { fr: "El Mehara", ar: "المحرة" },
  ],
}

export function wilayaOptions(lang) {
  return WILAYAS.map((w) => [w.code, `${w.code} — ${lang === 'ar' ? w.ar : w.fr}`])
}

export function communeOptions(wilayaCode, lang) {
  const list = COMMUNES_BY_WILAYA[wilayaCode] || []
  return list.map((c) => [c.fr, lang === 'ar' ? c.ar : c.fr])
}

export function wilayaLabel(code, lang) {
  const w = WILAYAS.find((x) => x.code === code)
  if (!w) return code || ''
  return `${w.code} — ${lang === 'ar' ? w.ar : w.fr}`
}

export function communeLabel(wilayaCode, communeFr, lang) {
  if (!communeFr) return ''
  if (lang !== 'ar') return communeFr
  const c = (COMMUNES_BY_WILAYA[wilayaCode] || []).find((x) => x.fr === communeFr)
  return c ? c.ar : communeFr
}
