# Generated by Django 5.1.5 on 2026-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('01', '01 — Adrar'), ('02', '02 — Chlef'), ('03', '03 — Laghouat'), ('04', '04 — Oum El Bouaghi'), ('05', '05 — Batna'), ('06', '06 — Bejaia'), ('07', '07 — Biskra'), ('08', '08 — Bechar'), ('09', '09 — Blida'), ('10', '10 — Bouira'), ('11', '11 — Tamenghasset'), ('12', '12 — Tebessa'), ('13', '13 — Tlemcen'), ('14', '14 — Tiaret'), ('15', '15 — Tizi Ouzou'), ('16', '16 — Alger'), ('17', '17 — Djelfa'), ('18', '18 — Jijel'), ('19', '19 — Setif'), ('20', '20 — Saida'), ('21', '21 — Skikda'), ('22', '22 — Sidi Bel Abbes'), ('23', '23 — Annaba'), ('24', '24 — Guelma'), ('25', '25 — Constantine'), ('26', '26 — Medea'), ('27', '27 — Mostaganem'), ('28', "28 — M'Sila"), ('29', '29 — Mascara'), ('30', '30 — Ouargla'), ('31', '31 — Oran'), ('32', '32 — El Bayadh'), ('33', '33 — Illizi'), ('34', '34 — Bordj Bou Arreridj'), ('35', '35 — Boumerdes'), ('36', '36 — El Tarf'), ('37', '37 — Tindouf'), ('38', '38 — Tissemsilt'), ('39', '39 — El Oued'), ('40', '40 — Khenchela'), ('41', '41 — Souk Ahras'), ('42', '42 — Tipaza'), ('43', '43 — Mila'), ('44', '44 — Ain Defla'), ('45', '45 — Naama'), ('46', '46 — Ain Temouchent'), ('47', '47 — Ghardaia'), ('48', '48 — Relizane'), ('49', '49 — Timimoun'), ('50', '50 — Bordj Badji Mokhtar'), ('51', '51 — Ouled Djellal'), ('52', '52 — Beni Abbes'), ('53', '53 — In Salah'), ('54', '54 — In Guezzam'), ('55', '55 — Touggourt'), ('56', '56 — Djanet'), ('57', '57 — El Megaier'), ('58', '58 — El Meniaa')], max_length=2, verbose_name='wilaya'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('01', '01 — Adrar'), ('02', '02 — Chlef'), ('03', '03 — Laghouat'), ('04', '04 — Oum El Bouaghi'), ('05', '05 — Batna'), ('06', '06 — Bejaia'), ('07', '07 — Biskra'), ('08', '08 — Bechar'), ('09', '09 — Blida'), ('10', '10 — Bouira'), ('11', '11 — Tamenghasset'), ('12', '12 — Tebessa'), ('13', '13 — Tlemcen'), ('14', '14 — Tiaret'), ('15', '15 — Tizi Ouzou'), ('16', '16 — Alger'), ('17', '17 — Djelfa'), ('18', '18 — Jijel'), ('19', '19 — Setif'), ('20', '20 — Saida'), ('21', '21 — Skikda'), ('22', '22 — Sidi Bel Abbes'), ('23', '23 — Annaba'), ('24', '24 — Guelma'), ('25', '25 — Constantine'), ('26', '26 — Medea'), ('27', '27 — Mostaganem'), ('28', "28 — M'Sila"), ('29', '29 — Mascara'), ('30', '30 — Ouargla'), ('31', '31 — Oran'), ('32', '32 — El Bayadh'), ('33', '33 — Illizi'), ('34', '34 — Bordj Bou Arreridj'), ('35', '35 — Boumerdes'), ('36', '36 — El Tarf'), ('37', '37 — Tindouf'), ('38', '38 — Tissemsilt'), ('39', '39 — El Oued'), ('40', '40 — Khenchela'), ('41', '41 — Souk Ahras'), ('42', '42 — Tipaza'), ('43', '43 — Mila'), ('44', '44 — Ain Defla'), ('45', '45 — Naama'), ('46', '46 — Ain Temouchent'), ('47', '47 — Ghardaia'), ('48', '48 — Relizane'), ('49', '49 — Timimoun'), ('50', '50 — Bordj Badji Mokhtar'), ('51', '51 — Ouled Djellal'), ('52', '52 — Beni Abbes'), ('53', '53 — In Salah'), ('54', '54 — In Guezzam'), ('55', '55 — Touggourt'), ('56', '56 — Djanet'), ('57', '57 — El Megaier'), ('58', '58 — El Meniaa')], max_length=2, verbose_name='wilaya'),
        ),
    ]
