# Generated by Django 5.1.5 on 2026-08-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_wilaya_alter_ownerprofile_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rc',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9/\\-]{5,30}$', 'Utilisez uniquement chiffres, lettres, « / » et « - ».')], verbose_name='registre de commerce'),
        ),
    ]
