# Generated by Django 5.1.5 on 2026-08-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, verbose_name='délai de livraison (jours)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèce'), ('certified_check', 'Chèque certifié'), ('transfer', 'Virement')], max_length=20, verbose_name='mode de paiement'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warranty_months',
            field=models.PositiveIntegerField(default=12, verbose_name='garantie (mois)'),
        ),
    ]
