# Generated by Django 5.1.5 on 2026-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_discount_purchaseorder_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèce'), ('certified_check', 'Chèque certifié'), ('transfer', 'Virement')], max_length=20, verbose_name='mode de paiement'),
        ),
    ]
