# Generated by Django 6.1 on 2026-08-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validé'), ('partial', 'Partiel'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('refused', 'Refusé')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('delivered_on', models.DateField(blank=True, null=True, verbose_name='date de livraison')),
                ('is_partial', models.BooleanField(default=False, verbose_name='livraison partielle')),
                ('received_by', models.CharField(blank=True, max_length=120, verbose_name='réceptionné par')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='signature')),
                ('stock_applied', models.BooleanField(default=False, verbose_name='stock mis à jour')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='partners.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'bon de livraison',
                'verbose_name_plural': 'bons de livraison',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('serial_numbers', models.TextField(blank=True, verbose_name='numéros de série')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validé'), ('partial', 'Partiel'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('refused', 'Refusé')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='validité')),
                ('payment_term', models.CharField(choices=[('cash', 'Comptant'), ('15', '15 jours'), ('30', '30 jours'), ('45', '45 jours'), ('60', '60 jours'), ('90', '90 jours')], default='30', max_length=10, verbose_name='conditions de paiement')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='délai de livraison (jours)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='partners.customercontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='partners.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='numéro')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validé'), ('partial', 'Partiel'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('refused', 'Refusé')], db_index=True, default='draft', max_length=12, verbose_name='statut')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant TTC')),
                ('notes', models.TextField(blank=True, verbose_name='observations')),
                ('payment_term', models.CharField(choices=[('cash', 'Comptant'), ('15', '15 jours'), ('30', '30 jours'), ('45', '45 jours'), ('60', '60 jours'), ('90', '90 jours')], default='30', max_length=10, verbose_name='conditions de paiement')),
                ('delivery_address', models.TextField(blank=True, verbose_name='adresse de livraison')),
                ('expected_on', models.DateField(blank=True, null=True, verbose_name='livraison prévue')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.customer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.quote')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'commande client',
                'verbose_name_plural': 'commandes clients',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='prix unitaire')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='remise (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='TVA (%)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='HT')),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TTC')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantité livrée')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='produit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
